
import java_swift
import java_util

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// class com.apple.eawt.AppEvent$OpenFilesEvent ///

open class AppEvent_OpenFilesEvent: AppEvent_FilesEvent {

    public convenience init?( casting object: java_swift.JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var AppEvent_OpenFilesEventJNIClass: jclass?

    /// final java.lang.String com.apple.eawt.AppEvent$OpenFilesEvent.searchTerm

    // Skipping field: true false false false false false 

    /// final java.util.List com.apple.eawt.AppEvent$FilesEvent.files

    // Skipping field: true false false false false false 

    /// private static final long java.util.EventObject.serialVersionUID

    /// protected transient java.lang.Object java.util.EventObject.source

    private static var source_FieldID: jfieldID?

    override open var source: java_swift.JavaObject! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "source", fieldType: "Ljava/lang/Object;", fieldCache: &AppEvent_OpenFilesEvent.source_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? java_swift.JavaObject( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "source", fieldType: "Ljava/lang/Object;", fieldCache: &AppEvent_OpenFilesEvent.source_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// com.apple.eawt.AppEvent$OpenFilesEvent(java.util.List,java.lang.String)

    // Skipping init: true false false 

    /// public java.lang.String com.apple.eawt.AppEvent$OpenFilesEvent.getSearchTerm()

    private static var getSearchTerm_MethodID_1: jmethodID?

    open func getSearchTerm() -> String! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getSearchTerm", methodSig: "()Ljava/lang/String;", methodCache: &AppEvent_OpenFilesEvent.getSearchTerm_MethodID_1, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? String( javaObject: __return ) : nil
    }


}

