
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home ///
/// Fri Aug 04 11:17:07 BST 2017 ///

/// interface com.apple.eawt.AppForegroundListener ///

public protocol AppForegroundListener: AppEventListener {

    /// public abstract void com.apple.eawt.AppForegroundListener.appRaisedToForeground(com.apple.eawt.AppEvent$AppForegroundEvent)

    func appRaisedToForeground( arg0: AppEvent_AppForegroundEvent? )

    /// public abstract void com.apple.eawt.AppForegroundListener.appMovedToBackground(com.apple.eawt.AppEvent$AppForegroundEvent)

    func appMovedToBackground( arg0: AppEvent_AppForegroundEvent? )

}


open class AppForegroundListenerForward: AppEventListenerForward, AppForegroundListener {

    private static var AppForegroundListenerJNIClass: jclass?

    /// public abstract void com.apple.eawt.AppForegroundListener.appRaisedToForeground(com.apple.eawt.AppEvent$AppForegroundEvent)

    private static var appRaisedToForeground_MethodID_3: jmethodID?

    open func appRaisedToForeground( arg0: AppEvent_AppForegroundEvent? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: arg0 != nil ? arg0! as JNIObject : nil, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "appRaisedToForeground", methodSig: "(Lcom/apple/eawt/AppEvent$AppForegroundEvent;)V", methodCache: &AppForegroundListenerForward.appRaisedToForeground_MethodID_3, args: &__args, locals: &__locals )
    }

    open func appRaisedToForeground( _ _arg0: AppEvent_AppForegroundEvent? ) {
        appRaisedToForeground( arg0: _arg0 )
    }

    /// public abstract void com.apple.eawt.AppForegroundListener.appMovedToBackground(com.apple.eawt.AppEvent$AppForegroundEvent)

    private static var appMovedToBackground_MethodID_4: jmethodID?

    open func appMovedToBackground( arg0: AppEvent_AppForegroundEvent? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: arg0 != nil ? arg0! as JNIObject : nil, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "appMovedToBackground", methodSig: "(Lcom/apple/eawt/AppEvent$AppForegroundEvent;)V", methodCache: &AppForegroundListenerForward.appMovedToBackground_MethodID_4, args: &__args, locals: &__locals )
    }

    open func appMovedToBackground( _ _arg0: AppEvent_AppForegroundEvent? ) {
        appMovedToBackground( arg0: _arg0 )
    }

}


private typealias AppForegroundListener_appRaisedToForeground_0_type = @convention(c) ( _: UnsafeMutablePointer<JNIEnv?>, _: jobject?, _: jlong, _: jobject? ) -> ()

private func AppForegroundListener_appRaisedToForeground_0( _ __env: UnsafeMutablePointer<JNIEnv?>, _ __this: jobject?, _ __swiftObject: jlong, _ arg0: jobject? ) -> () {
    JNI.inNative = true;
    AppForegroundListenerLocal_.swiftObject( jniEnv: __env, javaObject: __this, swiftObject: __swiftObject ).appRaisedToForeground( arg0: arg0 != nil ? AppEvent_AppForegroundEvent( javaObject: arg0 ) : nil )
    JNI.inNative = false;
}

private typealias AppForegroundListener_appMovedToBackground_1_type = @convention(c) ( _: UnsafeMutablePointer<JNIEnv?>, _: jobject?, _: jlong, _: jobject? ) -> ()

private func AppForegroundListener_appMovedToBackground_1( _ __env: UnsafeMutablePointer<JNIEnv?>, _ __this: jobject?, _ __swiftObject: jlong, _ arg0: jobject? ) -> () {
    JNI.inNative = true;
    AppForegroundListenerLocal_.swiftObject( jniEnv: __env, javaObject: __this, swiftObject: __swiftObject ).appMovedToBackground( arg0: arg0 != nil ? AppEvent_AppForegroundEvent( javaObject: arg0 ) : nil )
    JNI.inNative = false;
}

open class AppForegroundListenerLocal_: JNILocalProxy<AppForegroundListener, Any> {

    fileprivate static let _proxyClass: jclass = {
        var natives = [JNINativeMethod]()

        let AppForegroundListener_appRaisedToForeground_0_thunk: AppForegroundListener_appRaisedToForeground_0_type = AppForegroundListener_appRaisedToForeground_0
        natives.append( JNINativeMethod( name: strdup("__appRaisedToForeground"), signature: strdup("(JLcom/apple/eawt/AppEvent$AppForegroundEvent;)V"), fnPtr: unsafeBitCast( AppForegroundListener_appRaisedToForeground_0_thunk, to: UnsafeMutableRawPointer.self ) ) )

        let AppForegroundListener_appMovedToBackground_1_thunk: AppForegroundListener_appMovedToBackground_1_type = AppForegroundListener_appMovedToBackground_1
        natives.append( JNINativeMethod( name: strdup("__appMovedToBackground"), signature: strdup("(JLcom/apple/eawt/AppEvent$AppForegroundEvent;)V"), fnPtr: unsafeBitCast( AppForegroundListener_appMovedToBackground_1_thunk, to: UnsafeMutableRawPointer.self ) ) )

        natives.append( JNINativeMethod( name: strdup("__finalize"), signature: strdup("(J)V"), fnPtr: unsafeBitCast( JNIReleasableProxy__finalize_thunk, to: UnsafeMutableRawPointer.self ) ) )

        let clazz = JNI.FindClass( proxyClassName() )
        withUnsafePointer(to: &natives[0]) {
            nativesPtr in
            if JNI.api.RegisterNatives( JNI.env, clazz, nativesPtr, jint(natives.count) ) != jint(JNI_OK) {
                JNI.report( "Unable to register java natives" )
            }
        }

        defer { JNI.DeleteLocalRef( clazz ) }
        return JNI.api.NewGlobalRef( JNI.env, clazz )!
    }()

    override open class func proxyClassName() -> String { return "org/swiftjava/com_apple/AppForegroundListenerProxy" }
    override open class func proxyClass() -> jclass? { return _proxyClass }

}

extension AppForegroundListener {

    public func localJavaObject( _ locals: UnsafeMutablePointer<[jobject]> ) -> jobject? {
        return AppForegroundListenerLocal_( owned: self, proto: self ).localJavaObject( locals )
    }

}

open class AppForegroundListenerBase: AppForegroundListener {

    public init() {}

    /// public abstract void com.apple.eawt.AppForegroundListener.appRaisedToForeground(com.apple.eawt.AppEvent$AppForegroundEvent)

    open func appRaisedToForeground( arg0: AppEvent_AppForegroundEvent? ) /**/ {
    }

    open func appRaisedToForeground( _ _arg0: AppEvent_AppForegroundEvent? ) /**/ {
        appRaisedToForeground( arg0: _arg0 )
    }

    /// public abstract void com.apple.eawt.AppForegroundListener.appMovedToBackground(com.apple.eawt.AppEvent$AppForegroundEvent)

    open func appMovedToBackground( arg0: AppEvent_AppForegroundEvent? ) /**/ {
    }

    open func appMovedToBackground( _ _arg0: AppEvent_AppForegroundEvent? ) /**/ {
        appMovedToBackground( arg0: _arg0 )
    }

}
