
import java_swift
import java_lang
import javax_swing
import java_awt

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home ///
/// Tue Dec 20 11:52:09 GMT 2016 ///

/// class com.apple.laf.AquaTextPasswordFieldUI ///

open class AquaTextPasswordFieldUI: AquaTextFieldUI {

    public convenience init?( casting object: java_lang.JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        if !object.validDownCast( toJavaClass: "com.apple.laf.AquaTextPasswordFieldUI", file, line ) {
            return nil
        }
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var AquaTextPasswordFieldUIJNIClass: jclass?

    /// static final com.apple.laf.AquaUtils$LazySingleton com.apple.laf.AquaTextPasswordFieldUI.capsLockPainter

    /// protected com.apple.laf.AquaUtils$JComponentPainter com.apple.laf.AquaTextFieldUI.delegate

    private static var delegate_FieldID: jfieldID?

    override open var delegate: /* com.apple.laf.AquaUtils$JComponentPainter */ UnclassedProtocol! {
        get {
            var __locals = [jobject]()
            let __value = JNIField.GetObjectField( fieldName: "delegate", fieldType: "Lcom/apple/laf/AquaUtils$JComponentPainter;", fieldCache: &AquaTextPasswordFieldUI.delegate_FieldID, object: javaObject, locals: &__locals )
            return __value != nil ? /* com.apple.laf.AquaUtils$JComponentPainter */ UnclassedProtocolForward( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = jvalue( l: newValue?.localJavaObject( &__locals ) )
            JNIField.SetObjectField( fieldName: "delegate", fieldType: "Lcom/apple/laf/AquaUtils$JComponentPainter;", fieldCache: &AquaTextPasswordFieldUI.delegate_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// protected com.apple.laf.AquaFocusHandler com.apple.laf.AquaTextFieldUI.handler

    private static var handler_FieldID: jfieldID?

    override open var handler: AquaFocusHandler! {
        get {
            var __locals = [jobject]()
            let __value = JNIField.GetObjectField( fieldName: "handler", fieldType: "Lcom/apple/laf/AquaFocusHandler;", fieldCache: &AquaTextPasswordFieldUI.handler_FieldID, object: javaObject, locals: &__locals )
            return __value != nil ? AquaFocusHandler( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.encode( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "handler", fieldType: "Lcom/apple/laf/AquaFocusHandler;", fieldCache: &AquaTextPasswordFieldUI.handler_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// boolean com.apple.laf.AquaTextFieldUI.oldDragState

    /// private static javax.swing.plaf.basic.BasicTextUI$BasicCursor javax.swing.plaf.basic.BasicTextUI.textCursor

    /// private static final javax.swing.text.EditorKit javax.swing.plaf.basic.BasicTextUI.defaultKit

    /// transient javax.swing.text.JTextComponent javax.swing.plaf.basic.BasicTextUI.editor

    /// transient boolean javax.swing.plaf.basic.BasicTextUI.painted

    /// transient javax.swing.plaf.basic.BasicTextUI$RootView javax.swing.plaf.basic.BasicTextUI.rootView

    /// transient javax.swing.plaf.basic.BasicTextUI$UpdateHandler javax.swing.plaf.basic.BasicTextUI.updateHandler

    /// private static final javax.swing.TransferHandler javax.swing.plaf.basic.BasicTextUI.defaultTransferHandler

    /// private final javax.swing.plaf.basic.BasicTextUI$DragListener javax.swing.plaf.basic.BasicTextUI.dragListener

    /// private static final javax.swing.text.Position$Bias[] javax.swing.plaf.basic.BasicTextUI.discardBias

    /// private javax.swing.text.DefaultCaret javax.swing.plaf.basic.BasicTextUI.dropCaret

    /// public com.apple.laf.AquaTextPasswordFieldUI()

    private static var new_MethodID_1: jmethodID?

    public convenience init() {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __object = JNIMethod.NewObject( className: "com/apple/laf/AquaTextPasswordFieldUI", classCache: &AquaTextPasswordFieldUI.AquaTextPasswordFieldUIJNIClass, methodSig: "()V", methodCache: &AquaTextPasswordFieldUI.new_MethodID_1, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    /// static javax.swing.text.JTextComponent com.apple.laf.AquaTextPasswordFieldUI.access$000(com.apple.laf.AquaTextPasswordFieldUI)

    /// public javax.swing.text.View com.apple.laf.AquaTextPasswordFieldUI.create(javax.swing.text.Element)

    /// public static javax.swing.plaf.ComponentUI com.apple.laf.AquaTextPasswordFieldUI.createUI(javax.swing.JComponent)

    private static var createUI_MethodID_2: jmethodID?

    override open class func createUI( arg0: javax_swing.JComponent? ) -> javax_swing.ComponentUI! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaTextPasswordFieldUI", classCache: &AquaTextPasswordFieldUIJNIClass, methodName: "createUI", methodSig: "(Ljavax/swing/JComponent;)Ljavax/swing/plaf/ComponentUI;", methodCache: &createUI_MethodID_2, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? javax_swing.ComponentUI( javaObject: __return ) : nil
    }

    override open class func createUI( _ _arg0: javax_swing.JComponent? ) -> javax_swing.ComponentUI! {
        return createUI( arg0: _arg0 )
    }

    /// protected java.lang.String com.apple.laf.AquaTextPasswordFieldUI.getPropertyPrefix()

    private static var getPropertyPrefix_MethodID_3: jmethodID?

    override open func getPropertyPrefix() -> String! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getPropertyPrefix", methodSig: "()Ljava/lang/String;", methodCache: &AquaTextPasswordFieldUI.getPropertyPrefix_MethodID_3, args: &__args, locals: &__locals )
        return JNIType.decode( type: String(), from: __return )
    }


    /// protected void com.apple.laf.AquaTextPasswordFieldUI.installListeners()

    private static var installListeners_MethodID_4: jmethodID?

    override open func installListeners() {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "installListeners", methodSig: "()V", methodCache: &AquaTextPasswordFieldUI.installListeners_MethodID_4, args: &__args, locals: &__locals )
    }


    /// protected void com.apple.laf.AquaTextPasswordFieldUI.uninstallListeners()

    private static var uninstallListeners_MethodID_5: jmethodID?

    override open func uninstallListeners() {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "uninstallListeners", methodSig: "()V", methodCache: &AquaTextPasswordFieldUI.uninstallListeners_MethodID_5, args: &__args, locals: &__locals )
    }


    /// protected void com.apple.laf.AquaTextPasswordFieldUI.paintBackgroundSafely(java.awt.Graphics)

    private static var paintBackgroundSafely_MethodID_6: jmethodID?

    override open func paintBackgroundSafely( arg0: java_awt.Graphics? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "paintBackgroundSafely", methodSig: "(Ljava/awt/Graphics;)V", methodCache: &AquaTextPasswordFieldUI.paintBackgroundSafely_MethodID_6, args: &__args, locals: &__locals )
    }

    override open func paintBackgroundSafely( _ _arg0: java_awt.Graphics? ) {
        paintBackgroundSafely( arg0: _arg0 )
    }

    /// static com.apple.laf.AquaTextPasswordFieldUI$CapsLockSymbolPainter com.apple.laf.AquaTextPasswordFieldUI.getCapsLockPainter()

}
