
import java_swift
import java_awt
import java_lang
import javax_swing

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// class com.apple.laf.AquaTabbedPaneContrastUI ///

open class AquaTabbedPaneContrastUI: AquaTabbedPaneUI {

    public convenience init?( casting object: java_swift.JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var AquaTabbedPaneContrastUIJNIClass: jclass?

    /// private static final int com.apple.laf.AquaTabbedPaneUI.TAB_BORDER_INSET

    /// static com.apple.laf.AquaTabbedPaneUI$AlterRects[] com.apple.laf.AquaTabbedPaneUI.alterRects

    // Skipping field: true false false false false false 

    /// private static final int com.apple.laf.AquaTabbedPaneUI.kLargeTabHeight

    /// private static final int com.apple.laf.AquaTabbedPaneUI.kMaxIconSize

    /// private static final double com.apple.laf.AquaTabbedPaneUI.kNinetyDegrees

    /// private static final int com.apple.laf.AquaTabbedPaneUI.kSmallTabHeight

    /// protected final java.awt.Insets com.apple.laf.AquaTabbedPaneUI.contentDrawingInsets

    private static var contentDrawingInsets_FieldID: jfieldID?

    override open var contentDrawingInsets: java_awt.Insets! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "contentDrawingInsets", fieldType: "Ljava/awt/Insets;", fieldCache: &AquaTabbedPaneContrastUI.contentDrawingInsets_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? java_awt.Insets( javaObject: __value ) : nil
        }
    }

    /// protected final java.awt.Insets com.apple.laf.AquaTabbedPaneUI.currentContentBorderInsets

    private static var currentContentBorderInsets_FieldID: jfieldID?

    override open var currentContentBorderInsets: java_awt.Insets! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "currentContentBorderInsets", fieldType: "Ljava/awt/Insets;", fieldCache: &AquaTabbedPaneContrastUI.currentContentBorderInsets_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? java_awt.Insets( javaObject: __value ) : nil
        }
    }

    /// protected final java.awt.Insets com.apple.laf.AquaTabbedPaneUI.currentContentDrawingInsets

    private static var currentContentDrawingInsets_FieldID: jfieldID?

    override open var currentContentDrawingInsets: java_awt.Insets! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "currentContentDrawingInsets", fieldType: "Ljava/awt/Insets;", fieldCache: &AquaTabbedPaneContrastUI.currentContentDrawingInsets_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? java_awt.Insets( javaObject: __value ) : nil
        }
    }

    /// final java.awt.Rectangle com.apple.laf.AquaTabbedPaneUI.fContentRect

    // Skipping field: true false false false false false 

    /// final java.awt.Rectangle com.apple.laf.AquaTabbedPaneUI.fIconRect

    // Skipping field: true false false false false false 

    /// final java.awt.Rectangle com.apple.laf.AquaTabbedPaneUI.fTextRect

    // Skipping field: true false false false false false 

    /// protected boolean com.apple.laf.AquaTabbedPaneUI.hasAvoidedFirstFocus

    private static var hasAvoidedFirstFocus_FieldID: jfieldID?

    override open var hasAvoidedFirstFocus: Bool {
        get {
            let __value = JNIField.GetBooleanField( fieldName: "hasAvoidedFirstFocus", fieldType: "Z", fieldCache: &AquaTabbedPaneContrastUI.hasAvoidedFirstFocus_FieldID, object: javaObject )
            return __value != jboolean(JNI_FALSE)
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = jvalue( z: jboolean(newValue ? JNI_TRUE : JNI_FALSE) )
            JNIField.SetBooleanField( fieldName: "hasAvoidedFirstFocus", fieldType: "Z", fieldCache: &AquaTabbedPaneContrastUI.hasAvoidedFirstFocus_FieldID, object: javaObject, value: __value.z, locals: &__locals )
        }
    }

    /// protected java.lang.Boolean com.apple.laf.AquaTabbedPaneUI.isDefaultFocusReceiver

    private static var isDefaultFocusReceiver_FieldID: jfieldID?

    override open var isDefaultFocusReceiver: java_lang.Boolean! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "isDefaultFocusReceiver", fieldType: "Ljava/lang/Boolean;", fieldCache: &AquaTabbedPaneContrastUI.isDefaultFocusReceiver_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? java_lang.Boolean( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "isDefaultFocusReceiver", fieldType: "Ljava/lang/Boolean;", fieldCache: &AquaTabbedPaneContrastUI.isDefaultFocusReceiver_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// protected final com.apple.laf.AquaPainter com.apple.laf.AquaTabbedPaneUI.painter

    private static var painter_FieldID: jfieldID?

    override open var painter: /* class com.apple.laf.AquaPainter */ UnavailableObject! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "painter", fieldType: "Lcom/apple/laf/AquaPainter;", fieldCache: &AquaTabbedPaneContrastUI.painter_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? /* class com.apple.laf.AquaPainter */ UnavailableObject( javaObject: __value ) : nil
        }
    }

    /// protected boolean com.apple.laf.AquaTabbedPaneUI.popupSelectionChanged

    private static var popupSelectionChanged_FieldID: jfieldID?

    override open var popupSelectionChanged: Bool {
        get {
            let __value = JNIField.GetBooleanField( fieldName: "popupSelectionChanged", fieldType: "Z", fieldCache: &AquaTabbedPaneContrastUI.popupSelectionChanged_FieldID, object: javaObject )
            return __value != jboolean(JNI_FALSE)
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = jvalue( z: jboolean(newValue ? JNI_TRUE : JNI_FALSE) )
            JNIField.SetBooleanField( fieldName: "popupSelectionChanged", fieldType: "Z", fieldCache: &AquaTabbedPaneContrastUI.popupSelectionChanged_FieldID, object: javaObject, value: __value.z, locals: &__locals )
        }
    }

    /// protected int com.apple.laf.AquaTabbedPaneUI.pressedTab

    private static var pressedTab_FieldID: jfieldID?

    override open var pressedTab: Int {
        get {
            let __value = JNIField.GetIntField( fieldName: "pressedTab", fieldType: "I", fieldCache: &AquaTabbedPaneContrastUI.pressedTab_FieldID, object: javaObject )
            return Int(__value)
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = jvalue( i: jint(newValue) )
            JNIField.SetIntField( fieldName: "pressedTab", fieldType: "I", fieldCache: &AquaTabbedPaneContrastUI.pressedTab_FieldID, object: javaObject, value: __value.i, locals: &__locals )
        }
    }

    /// protected final com.apple.laf.AquaTabbedPaneTabState com.apple.laf.AquaTabbedPaneUI.visibleTabState

    private static var visibleTabState_FieldID: jfieldID?

    override open var visibleTabState: /* class com.apple.laf.AquaTabbedPaneTabState */ UnavailableObject! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "visibleTabState", fieldType: "Lcom/apple/laf/AquaTabbedPaneTabState;", fieldCache: &AquaTabbedPaneContrastUI.visibleTabState_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? /* class com.apple.laf.AquaTabbedPaneTabState */ UnavailableObject( javaObject: __value ) : nil
        }
    }

    /// private static final int com.apple.laf.AquaTabbedPaneCopyFromBasicUI.CROP_SEGMENT

    /// private static int[] com.apple.laf.AquaTabbedPaneCopyFromBasicUI.xCropLen

    /// private static int[] com.apple.laf.AquaTabbedPaneCopyFromBasicUI.yCropLen

    /// private int com.apple.laf.AquaTabbedPaneCopyFromBasicUI.baseline

    /// protected transient java.awt.Rectangle com.apple.laf.AquaTabbedPaneCopyFromBasicUI.calcRect

    private static var calcRect_FieldID: jfieldID?

    override open var calcRect: java_awt.Rectangle! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "calcRect", fieldType: "Ljava/awt/Rectangle;", fieldCache: &AquaTabbedPaneContrastUI.calcRect_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? java_awt.Rectangle( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "calcRect", fieldType: "Ljava/awt/Rectangle;", fieldCache: &AquaTabbedPaneContrastUI.calcRect_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// private boolean com.apple.laf.AquaTabbedPaneCopyFromBasicUI.calculatedBaseline

    /// protected java.awt.Insets com.apple.laf.AquaTabbedPaneCopyFromBasicUI.contentBorderInsets

    private static var contentBorderInsets_FieldID: jfieldID?

    override open var contentBorderInsets: java_awt.Insets! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "contentBorderInsets", fieldType: "Ljava/awt/Insets;", fieldCache: &AquaTabbedPaneContrastUI.contentBorderInsets_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? java_awt.Insets( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "contentBorderInsets", fieldType: "Ljava/awt/Insets;", fieldCache: &AquaTabbedPaneContrastUI.contentBorderInsets_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// private boolean com.apple.laf.AquaTabbedPaneCopyFromBasicUI.contentOpaque

    /// private final java.awt.Insets com.apple.laf.AquaTabbedPaneCopyFromBasicUI.currentPadInsets

    /// private final java.awt.Insets com.apple.laf.AquaTabbedPaneCopyFromBasicUI.currentTabAreaInsets

    /// protected java.awt.Color com.apple.laf.AquaTabbedPaneCopyFromBasicUI.darkShadow

    private static var darkShadow_FieldID: jfieldID?

    override open var darkShadow: java_awt.Color! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "darkShadow", fieldType: "Ljava/awt/Color;", fieldCache: &AquaTabbedPaneContrastUI.darkShadow_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? java_awt.Color( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "darkShadow", fieldType: "Ljava/awt/Color;", fieldCache: &AquaTabbedPaneContrastUI.darkShadow_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// protected javax.swing.KeyStroke com.apple.laf.AquaTabbedPaneCopyFromBasicUI.downKey

    private static var downKey_FieldID: jfieldID?

    override open var downKey: javax_swing.KeyStroke! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "downKey", fieldType: "Ljavax/swing/KeyStroke;", fieldCache: &AquaTabbedPaneContrastUI.downKey_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? javax_swing.KeyStroke( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "downKey", fieldType: "Ljavax/swing/KeyStroke;", fieldCache: &AquaTabbedPaneContrastUI.downKey_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// protected java.awt.Color com.apple.laf.AquaTabbedPaneCopyFromBasicUI.focus

    private static var focus_FieldID: jfieldID?

    override open var focus: java_awt.Color! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "focus", fieldType: "Ljava/awt/Color;", fieldCache: &AquaTabbedPaneContrastUI.focus_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? java_awt.Color( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "focus", fieldType: "Ljava/awt/Color;", fieldCache: &AquaTabbedPaneContrastUI.focus_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// private int com.apple.laf.AquaTabbedPaneCopyFromBasicUI.focusIndex

    /// protected java.awt.event.FocusListener com.apple.laf.AquaTabbedPaneCopyFromBasicUI.focusListener

    private static var focusListener_FieldID: jfieldID?

    override open var focusListener: java_awt.FocusListener! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "focusListener", fieldType: "Ljava/awt/event/FocusListener;", fieldCache: &AquaTabbedPaneContrastUI.focusListener_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? java_awt.FocusListenerForward( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "focusListener", fieldType: "Ljava/awt/event/FocusListener;", fieldCache: &AquaTabbedPaneContrastUI.focusListener_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// private com.apple.laf.AquaTabbedPaneCopyFromBasicUI$Handler com.apple.laf.AquaTabbedPaneCopyFromBasicUI.handler

    /// protected java.awt.Color com.apple.laf.AquaTabbedPaneCopyFromBasicUI.highlight

    private static var highlight_FieldID: jfieldID?

    override open var highlight: java_awt.Color! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "highlight", fieldType: "Ljava/awt/Color;", fieldCache: &AquaTabbedPaneContrastUI.highlight_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? java_awt.Color( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "highlight", fieldType: "Ljava/awt/Color;", fieldCache: &AquaTabbedPaneContrastUI.highlight_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// private java.util.Vector com.apple.laf.AquaTabbedPaneCopyFromBasicUI.htmlViews

    /// private boolean com.apple.laf.AquaTabbedPaneCopyFromBasicUI.isRunsDirty

    /// protected javax.swing.KeyStroke com.apple.laf.AquaTabbedPaneCopyFromBasicUI.leftKey

    private static var leftKey_FieldID: jfieldID?

    override open var leftKey: javax_swing.KeyStroke! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "leftKey", fieldType: "Ljavax/swing/KeyStroke;", fieldCache: &AquaTabbedPaneContrastUI.leftKey_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? javax_swing.KeyStroke( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "leftKey", fieldType: "Ljavax/swing/KeyStroke;", fieldCache: &AquaTabbedPaneContrastUI.leftKey_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// protected java.awt.Color com.apple.laf.AquaTabbedPaneCopyFromBasicUI.lightHighlight

    private static var lightHighlight_FieldID: jfieldID?

    override open var lightHighlight: java_awt.Color! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "lightHighlight", fieldType: "Ljava/awt/Color;", fieldCache: &AquaTabbedPaneContrastUI.lightHighlight_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? java_awt.Color( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "lightHighlight", fieldType: "Ljava/awt/Color;", fieldCache: &AquaTabbedPaneContrastUI.lightHighlight_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// protected int com.apple.laf.AquaTabbedPaneCopyFromBasicUI.maxTabHeight

    private static var maxTabHeight_FieldID: jfieldID?

    override open var maxTabHeight: Int {
        get {
            let __value = JNIField.GetIntField( fieldName: "maxTabHeight", fieldType: "I", fieldCache: &AquaTabbedPaneContrastUI.maxTabHeight_FieldID, object: javaObject )
            return Int(__value)
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = jvalue( i: jint(newValue) )
            JNIField.SetIntField( fieldName: "maxTabHeight", fieldType: "I", fieldCache: &AquaTabbedPaneContrastUI.maxTabHeight_FieldID, object: javaObject, value: __value.i, locals: &__locals )
        }
    }

    /// protected int com.apple.laf.AquaTabbedPaneCopyFromBasicUI.maxTabWidth

    private static var maxTabWidth_FieldID: jfieldID?

    override open var maxTabWidth: Int {
        get {
            let __value = JNIField.GetIntField( fieldName: "maxTabWidth", fieldType: "I", fieldCache: &AquaTabbedPaneContrastUI.maxTabWidth_FieldID, object: javaObject )
            return Int(__value)
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = jvalue( i: jint(newValue) )
            JNIField.SetIntField( fieldName: "maxTabWidth", fieldType: "I", fieldCache: &AquaTabbedPaneContrastUI.maxTabWidth_FieldID, object: javaObject, value: __value.i, locals: &__locals )
        }
    }

    /// private javax.swing.InputMap com.apple.laf.AquaTabbedPaneCopyFromBasicUI.mnemonicInputMap

    /// private java.util.Hashtable com.apple.laf.AquaTabbedPaneCopyFromBasicUI.mnemonicToIndexMap

    /// protected java.awt.event.MouseListener com.apple.laf.AquaTabbedPaneCopyFromBasicUI.mouseListener

    private static var mouseListener_FieldID: jfieldID?

    override open var mouseListener: java_awt.MouseListener! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "mouseListener", fieldType: "Ljava/awt/event/MouseListener;", fieldCache: &AquaTabbedPaneContrastUI.mouseListener_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? java_awt.MouseListenerForward( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "mouseListener", fieldType: "Ljava/awt/event/MouseListener;", fieldCache: &AquaTabbedPaneContrastUI.mouseListener_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// protected java.beans.PropertyChangeListener com.apple.laf.AquaTabbedPaneCopyFromBasicUI.propertyChangeListener

    private static var propertyChangeListener_FieldID: jfieldID?

    override open var propertyChangeListener: /* interface java.beans.PropertyChangeListener */ UnavailableProtocol! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "propertyChangeListener", fieldType: "Ljava/beans/PropertyChangeListener;", fieldCache: &AquaTabbedPaneContrastUI.propertyChangeListener_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? /* interface java.beans.PropertyChangeListener */ UnavailableProtocolForward( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "propertyChangeListener", fieldType: "Ljava/beans/PropertyChangeListener;", fieldCache: &AquaTabbedPaneContrastUI.propertyChangeListener_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// protected java.awt.Rectangle[] com.apple.laf.AquaTabbedPaneCopyFromBasicUI.rects

    private static var rects_FieldID: jfieldID?

    override open var rects: [Rectangle]! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "rects", fieldType: "[Ljava/awt/Rectangle;", fieldCache: &AquaTabbedPaneContrastUI.rects_FieldID, object: javaObject )
            return JNIType.toSwift( type: [Rectangle].self, from: __value )
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "rects", fieldType: "[Ljava/awt/Rectangle;", fieldCache: &AquaTabbedPaneContrastUI.rects_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// protected javax.swing.KeyStroke com.apple.laf.AquaTabbedPaneCopyFromBasicUI.rightKey

    private static var rightKey_FieldID: jfieldID?

    override open var rightKey: javax_swing.KeyStroke! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "rightKey", fieldType: "Ljavax/swing/KeyStroke;", fieldCache: &AquaTabbedPaneContrastUI.rightKey_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? javax_swing.KeyStroke( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "rightKey", fieldType: "Ljavax/swing/KeyStroke;", fieldCache: &AquaTabbedPaneContrastUI.rightKey_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// private int com.apple.laf.AquaTabbedPaneCopyFromBasicUI.rolloverTabIndex

    /// protected int com.apple.laf.AquaTabbedPaneCopyFromBasicUI.runCount

    private static var runCount_FieldID: jfieldID?

    override open var runCount: Int {
        get {
            let __value = JNIField.GetIntField( fieldName: "runCount", fieldType: "I", fieldCache: &AquaTabbedPaneContrastUI.runCount_FieldID, object: javaObject )
            return Int(__value)
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = jvalue( i: jint(newValue) )
            JNIField.SetIntField( fieldName: "runCount", fieldType: "I", fieldCache: &AquaTabbedPaneContrastUI.runCount_FieldID, object: javaObject, value: __value.i, locals: &__locals )
        }
    }

    /// private java.awt.Color com.apple.laf.AquaTabbedPaneCopyFromBasicUI.selectedColor

    /// protected int com.apple.laf.AquaTabbedPaneCopyFromBasicUI.selectedRun

    private static var selectedRun_FieldID: jfieldID?

    override open var selectedRun: Int {
        get {
            let __value = JNIField.GetIntField( fieldName: "selectedRun", fieldType: "I", fieldCache: &AquaTabbedPaneContrastUI.selectedRun_FieldID, object: javaObject )
            return Int(__value)
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = jvalue( i: jint(newValue) )
            JNIField.SetIntField( fieldName: "selectedRun", fieldType: "I", fieldCache: &AquaTabbedPaneContrastUI.selectedRun_FieldID, object: javaObject, value: __value.i, locals: &__locals )
        }
    }

    /// protected java.awt.Insets com.apple.laf.AquaTabbedPaneCopyFromBasicUI.selectedTabPadInsets

    private static var selectedTabPadInsets_FieldID: jfieldID?

    override open var selectedTabPadInsets: java_awt.Insets! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "selectedTabPadInsets", fieldType: "Ljava/awt/Insets;", fieldCache: &AquaTabbedPaneContrastUI.selectedTabPadInsets_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? java_awt.Insets( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "selectedTabPadInsets", fieldType: "Ljava/awt/Insets;", fieldCache: &AquaTabbedPaneContrastUI.selectedTabPadInsets_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// protected java.awt.Color com.apple.laf.AquaTabbedPaneCopyFromBasicUI.shadow

    private static var shadow_FieldID: jfieldID?

    override open var shadow: java_awt.Color! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "shadow", fieldType: "Ljava/awt/Color;", fieldCache: &AquaTabbedPaneContrastUI.shadow_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? java_awt.Color( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "shadow", fieldType: "Ljava/awt/Color;", fieldCache: &AquaTabbedPaneContrastUI.shadow_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// protected java.awt.Insets com.apple.laf.AquaTabbedPaneCopyFromBasicUI.tabAreaInsets

    private static var tabAreaInsets_FieldID: jfieldID?

    override open var tabAreaInsets: java_awt.Insets! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "tabAreaInsets", fieldType: "Ljava/awt/Insets;", fieldCache: &AquaTabbedPaneContrastUI.tabAreaInsets_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? java_awt.Insets( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "tabAreaInsets", fieldType: "Ljava/awt/Insets;", fieldCache: &AquaTabbedPaneContrastUI.tabAreaInsets_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// protected javax.swing.event.ChangeListener com.apple.laf.AquaTabbedPaneCopyFromBasicUI.tabChangeListener

    private static var tabChangeListener_FieldID: jfieldID?

    override open var tabChangeListener: javax_swing.ChangeListener! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "tabChangeListener", fieldType: "Ljavax/swing/event/ChangeListener;", fieldCache: &AquaTabbedPaneContrastUI.tabChangeListener_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? javax_swing.ChangeListenerForward( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "tabChangeListener", fieldType: "Ljavax/swing/event/ChangeListener;", fieldCache: &AquaTabbedPaneContrastUI.tabChangeListener_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// private com.apple.laf.AquaTabbedPaneCopyFromBasicUI$TabContainer com.apple.laf.AquaTabbedPaneCopyFromBasicUI.tabContainer

    /// protected java.awt.Insets com.apple.laf.AquaTabbedPaneCopyFromBasicUI.tabInsets

    private static var tabInsets_FieldID: jfieldID?

    override open var tabInsets: java_awt.Insets! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "tabInsets", fieldType: "Ljava/awt/Insets;", fieldCache: &AquaTabbedPaneContrastUI.tabInsets_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? java_awt.Insets( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "tabInsets", fieldType: "Ljava/awt/Insets;", fieldCache: &AquaTabbedPaneContrastUI.tabInsets_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// protected javax.swing.JTabbedPane com.apple.laf.AquaTabbedPaneCopyFromBasicUI.tabPane

    private static var tabPane_FieldID: jfieldID?

    override open var tabPane: javax_swing.JTabbedPane! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "tabPane", fieldType: "Ljavax/swing/JTabbedPane;", fieldCache: &AquaTabbedPaneContrastUI.tabPane_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? javax_swing.JTabbedPane( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "tabPane", fieldType: "Ljavax/swing/JTabbedPane;", fieldCache: &AquaTabbedPaneContrastUI.tabPane_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// protected int com.apple.laf.AquaTabbedPaneCopyFromBasicUI.tabRunOverlay

    private static var tabRunOverlay_FieldID: jfieldID?

    override open var tabRunOverlay: Int {
        get {
            let __value = JNIField.GetIntField( fieldName: "tabRunOverlay", fieldType: "I", fieldCache: &AquaTabbedPaneContrastUI.tabRunOverlay_FieldID, object: javaObject )
            return Int(__value)
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = jvalue( i: jint(newValue) )
            JNIField.SetIntField( fieldName: "tabRunOverlay", fieldType: "I", fieldCache: &AquaTabbedPaneContrastUI.tabRunOverlay_FieldID, object: javaObject, value: __value.i, locals: &__locals )
        }
    }

    /// protected int[] com.apple.laf.AquaTabbedPaneCopyFromBasicUI.tabRuns

    private static var tabRuns_FieldID: jfieldID?

    override open var tabRuns: [Int32]! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "tabRuns", fieldType: "[I", fieldCache: &AquaTabbedPaneContrastUI.tabRuns_FieldID, object: javaObject )
            return JNIType.toSwift( type: [Int32].self, from: __value )
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "tabRuns", fieldType: "[I", fieldCache: &AquaTabbedPaneContrastUI.tabRuns_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// private com.apple.laf.AquaTabbedPaneCopyFromBasicUI$ScrollableTabSupport com.apple.laf.AquaTabbedPaneCopyFromBasicUI.tabScroller

    /// private boolean com.apple.laf.AquaTabbedPaneCopyFromBasicUI.tabsOpaque

    /// private boolean com.apple.laf.AquaTabbedPaneCopyFromBasicUI.tabsOverlapBorder

    /// protected int com.apple.laf.AquaTabbedPaneCopyFromBasicUI.textIconGap

    private static var textIconGap_FieldID: jfieldID?

    override open var textIconGap: Int {
        get {
            let __value = JNIField.GetIntField( fieldName: "textIconGap", fieldType: "I", fieldCache: &AquaTabbedPaneContrastUI.textIconGap_FieldID, object: javaObject )
            return Int(__value)
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = jvalue( i: jint(newValue) )
            JNIField.SetIntField( fieldName: "textIconGap", fieldType: "I", fieldCache: &AquaTabbedPaneContrastUI.textIconGap_FieldID, object: javaObject, value: __value.i, locals: &__locals )
        }
    }

    /// protected javax.swing.KeyStroke com.apple.laf.AquaTabbedPaneCopyFromBasicUI.upKey

    private static var upKey_FieldID: jfieldID?

    override open var upKey: javax_swing.KeyStroke! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "upKey", fieldType: "Ljavax/swing/KeyStroke;", fieldCache: &AquaTabbedPaneContrastUI.upKey_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? javax_swing.KeyStroke( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "upKey", fieldType: "Ljavax/swing/KeyStroke;", fieldCache: &AquaTabbedPaneContrastUI.upKey_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// private java.awt.Component com.apple.laf.AquaTabbedPaneCopyFromBasicUI.visibleComponent

    /// public static final int javax.swing.SwingConstants.BOTTOM

    // Skipping field: false true false false false false 

    /// public static final int javax.swing.SwingConstants.CENTER

    // Skipping field: false true false false false false 

    /// public static final int javax.swing.SwingConstants.EAST

    // Skipping field: false true false false false false 

    /// public static final int javax.swing.SwingConstants.HORIZONTAL

    // Skipping field: false true false false false false 

    /// public static final int javax.swing.SwingConstants.LEADING

    // Skipping field: false true false false false false 

    /// public static final int javax.swing.SwingConstants.LEFT

    // Skipping field: false true false false false false 

    /// public static final int javax.swing.SwingConstants.NEXT

    // Skipping field: false true false false false false 

    /// public static final int javax.swing.SwingConstants.NORTH

    // Skipping field: false true false false false false 

    /// public static final int javax.swing.SwingConstants.NORTH_EAST

    // Skipping field: false true false false false false 

    /// public static final int javax.swing.SwingConstants.NORTH_WEST

    // Skipping field: false true false false false false 

    /// public static final int javax.swing.SwingConstants.PREVIOUS

    // Skipping field: false true false false false false 

    /// public static final int javax.swing.SwingConstants.RIGHT

    // Skipping field: false true false false false false 

    /// public static final int javax.swing.SwingConstants.SOUTH

    // Skipping field: false true false false false false 

    /// public static final int javax.swing.SwingConstants.SOUTH_EAST

    // Skipping field: false true false false false false 

    /// public static final int javax.swing.SwingConstants.SOUTH_WEST

    // Skipping field: false true false false false false 

    /// public static final int javax.swing.SwingConstants.TOP

    // Skipping field: false true false false false false 

    /// public static final int javax.swing.SwingConstants.TRAILING

    // Skipping field: false true false false false false 

    /// public static final int javax.swing.SwingConstants.VERTICAL

    // Skipping field: false true false false false false 

    /// public static final int javax.swing.SwingConstants.WEST

    // Skipping field: false true false false false false 

    /// public com.apple.laf.AquaTabbedPaneContrastUI()

    private static var new_MethodID_1: jmethodID?

    public convenience init() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __object = JNIMethod.NewObject( className: "com/apple/laf/AquaTabbedPaneContrastUI", classCache: &AquaTabbedPaneContrastUI.AquaTabbedPaneContrastUIJNIClass, methodSig: "()V", methodCache: &AquaTabbedPaneContrastUI.new_MethodID_1, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    /// public static javax.swing.plaf.ComponentUI com.apple.laf.AquaTabbedPaneContrastUI.createUI(javax.swing.JComponent)

    private static var createUI_MethodID_2: jmethodID?

    override open class func createUI( arg0: javax_swing.JComponent? ) -> javax_swing.ComponentUI! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaTabbedPaneContrastUI", classCache: &AquaTabbedPaneContrastUIJNIClass, methodName: "createUI", methodSig: "(Ljavax/swing/JComponent;)Ljavax/swing/plaf/ComponentUI;", methodCache: &createUI_MethodID_2, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? javax_swing.ComponentUI( javaObject: __return ) : nil
    }

    override open class func createUI( _ _arg0: javax_swing.JComponent? ) -> javax_swing.ComponentUI! {
        return createUI( arg0: _arg0 )
    }

    /// protected static java.awt.Color com.apple.laf.AquaTabbedPaneContrastUI.getNonSelectedTabTitleColor()

    private static var getNonSelectedTabTitleColor_MethodID_3: jmethodID?

    open class func getNonSelectedTabTitleColor() -> java_awt.Color! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaTabbedPaneContrastUI", classCache: &AquaTabbedPaneContrastUIJNIClass, methodName: "getNonSelectedTabTitleColor", methodSig: "()Ljava/awt/Color;", methodCache: &getNonSelectedTabTitleColor_MethodID_3, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_awt.Color( javaObject: __return ) : nil
    }


    /// protected static java.awt.Color com.apple.laf.AquaTabbedPaneContrastUI.getSelectedTabTitleColor(boolean,boolean)

    private static var getSelectedTabTitleColor_MethodID_4: jmethodID?

    open class func getSelectedTabTitleColor( arg0: Bool, arg1: Bool ) -> java_awt.Color! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        __args[0] = jvalue( z: jboolean(arg0 ? JNI_TRUE : JNI_FALSE) )
        __args[1] = jvalue( z: jboolean(arg1 ? JNI_TRUE : JNI_FALSE) )
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaTabbedPaneContrastUI", classCache: &AquaTabbedPaneContrastUIJNIClass, methodName: "getSelectedTabTitleColor", methodSig: "(ZZ)Ljava/awt/Color;", methodCache: &getSelectedTabTitleColor_MethodID_4, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_awt.Color( javaObject: __return ) : nil
    }

    open class func getSelectedTabTitleColor( _ _arg0: Bool, _ _arg1: Bool ) -> java_awt.Color! {
        return getSelectedTabTitleColor( arg0: _arg0, arg1: _arg1 )
    }

    /// protected static java.awt.Color com.apple.laf.AquaTabbedPaneContrastUI.getSelectedTabTitleShadowColor(boolean)

    private static var getSelectedTabTitleShadowColor_MethodID_5: jmethodID?

    open class func getSelectedTabTitleShadowColor( arg0: Bool ) -> java_awt.Color! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = jvalue( z: jboolean(arg0 ? JNI_TRUE : JNI_FALSE) )
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaTabbedPaneContrastUI", classCache: &AquaTabbedPaneContrastUIJNIClass, methodName: "getSelectedTabTitleShadowColor", methodSig: "(Z)Ljava/awt/Color;", methodCache: &getSelectedTabTitleShadowColor_MethodID_5, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_awt.Color( javaObject: __return ) : nil
    }

    open class func getSelectedTabTitleShadowColor( _ _arg0: Bool ) -> java_awt.Color! {
        return getSelectedTabTitleShadowColor( arg0: _arg0 )
    }

    /// protected apple.laf.JRSUIConstants$SegmentLeadingSeparator com.apple.laf.AquaTabbedPaneContrastUI.getSegmentLeadingSeparator(int,int,boolean)

    private static var getSegmentLeadingSeparator_MethodID_6: jmethodID?

    override open func getSegmentLeadingSeparator( arg0: Int, arg1: Int, arg2: Bool ) -> /* class apple.laf.JRSUIConstants$SegmentLeadingSeparator */ UnavailableObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 3 )
        __args[0] = jvalue( i: jint(arg0) )
        __args[1] = jvalue( i: jint(arg1) )
        __args[2] = jvalue( z: jboolean(arg2 ? JNI_TRUE : JNI_FALSE) )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getSegmentLeadingSeparator", methodSig: "(IIZ)Lapple/laf/JRSUIConstants$SegmentLeadingSeparator;", methodCache: &AquaTabbedPaneContrastUI.getSegmentLeadingSeparator_MethodID_6, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? /* class apple.laf.JRSUIConstants$SegmentLeadingSeparator */ UnavailableObject( javaObject: __return ) : nil
    }

    override open func getSegmentLeadingSeparator( _ _arg0: Int, _ _arg1: Int, _ _arg2: Bool ) -> /* class apple.laf.JRSUIConstants$SegmentLeadingSeparator */ UnavailableObject! {
        return getSegmentLeadingSeparator( arg0: _arg0, arg1: _arg1, arg2: _arg2 )
    }

    /// protected apple.laf.JRSUIConstants$SegmentTrailingSeparator com.apple.laf.AquaTabbedPaneContrastUI.getSegmentTrailingSeparator(int,int,boolean)

    private static var getSegmentTrailingSeparator_MethodID_7: jmethodID?

    override open func getSegmentTrailingSeparator( arg0: Int, arg1: Int, arg2: Bool ) -> /* class apple.laf.JRSUIConstants$SegmentTrailingSeparator */ UnavailableObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 3 )
        __args[0] = jvalue( i: jint(arg0) )
        __args[1] = jvalue( i: jint(arg1) )
        __args[2] = jvalue( z: jboolean(arg2 ? JNI_TRUE : JNI_FALSE) )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getSegmentTrailingSeparator", methodSig: "(IIZ)Lapple/laf/JRSUIConstants$SegmentTrailingSeparator;", methodCache: &AquaTabbedPaneContrastUI.getSegmentTrailingSeparator_MethodID_7, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? /* class apple.laf.JRSUIConstants$SegmentTrailingSeparator */ UnavailableObject( javaObject: __return ) : nil
    }

    override open func getSegmentTrailingSeparator( _ _arg0: Int, _ _arg1: Int, _ _arg2: Bool ) -> /* class apple.laf.JRSUIConstants$SegmentTrailingSeparator */ UnavailableObject! {
        return getSegmentTrailingSeparator( arg0: _arg0, arg1: _arg1, arg2: _arg2 )
    }

    /// protected apple.laf.JRSUIConstants$State com.apple.laf.AquaTabbedPaneContrastUI.getState(int,boolean,boolean)

    private static var getState_MethodID_8: jmethodID?

    override open func getState( arg0: Int, arg1: Bool, arg2: Bool ) -> /* class apple.laf.JRSUIConstants$State */ UnavailableObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 3 )
        __args[0] = jvalue( i: jint(arg0) )
        __args[1] = jvalue( z: jboolean(arg1 ? JNI_TRUE : JNI_FALSE) )
        __args[2] = jvalue( z: jboolean(arg2 ? JNI_TRUE : JNI_FALSE) )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getState", methodSig: "(IZZ)Lapple/laf/JRSUIConstants$State;", methodCache: &AquaTabbedPaneContrastUI.getState_MethodID_8, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? /* class apple.laf.JRSUIConstants$State */ UnavailableObject( javaObject: __return ) : nil
    }

    override open func getState( _ _arg0: Int, _ _arg1: Bool, _ _arg2: Bool ) -> /* class apple.laf.JRSUIConstants$State */ UnavailableObject! {
        return getState( arg0: _arg0, arg1: _arg1, arg2: _arg2 )
    }

    /// protected boolean com.apple.laf.AquaTabbedPaneContrastUI.isPressedAt(int)

    private static var isPressedAt_MethodID_9: jmethodID?

    open func isPressedAt( arg0: Int ) -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = jvalue( i: jint(arg0) )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "isPressedAt", methodSig: "(I)Z", methodCache: &AquaTabbedPaneContrastUI.isPressedAt_MethodID_9, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }

    open func isPressedAt( _ _arg0: Int ) -> Bool {
        return isPressedAt( arg0: _arg0 )
    }

    /// protected void com.apple.laf.AquaTabbedPaneContrastUI.paintTitle(java.awt.Graphics2D,java.awt.Font,java.awt.FontMetrics,java.awt.Rectangle,int,java.lang.String)

    private static var paintTitle_MethodID_10: jmethodID?

    override open func paintTitle( arg0: java_awt.Graphics2D?, arg1: java_awt.Font?, arg2: java_awt.FontMetrics?, arg3: java_awt.Rectangle?, arg4: Int, arg5: String? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 6 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        __args[1] = JNIType.toJava( value: arg1, locals: &__locals )
        __args[2] = JNIType.toJava( value: arg2, locals: &__locals )
        __args[3] = JNIType.toJava( value: arg3, locals: &__locals )
        __args[4] = jvalue( i: jint(arg4) )
        __args[5] = JNIType.toJava( value: arg5, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "paintTitle", methodSig: "(Ljava/awt/Graphics2D;Ljava/awt/Font;Ljava/awt/FontMetrics;Ljava/awt/Rectangle;ILjava/lang/String;)V", methodCache: &AquaTabbedPaneContrastUI.paintTitle_MethodID_10, args: &__args, locals: &__locals )
    }

    override open func paintTitle( _ _arg0: java_awt.Graphics2D?, _ _arg1: java_awt.Font?, _ _arg2: java_awt.FontMetrics?, _ _arg3: java_awt.Rectangle?, _ _arg4: Int, _ _arg5: String? ) {
        paintTitle( arg0: _arg0, arg1: _arg1, arg2: _arg2, arg3: _arg3, arg4: _arg4, arg5: _arg5 )
    }

    /// protected boolean com.apple.laf.AquaTabbedPaneContrastUI.shouldRepaintSelectedTabOnMouseDown()

    private static var shouldRepaintSelectedTabOnMouseDown_MethodID_11: jmethodID?

    override open func shouldRepaintSelectedTabOnMouseDown() -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "shouldRepaintSelectedTabOnMouseDown", methodSig: "()Z", methodCache: &AquaTabbedPaneContrastUI.shouldRepaintSelectedTabOnMouseDown_MethodID_11, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }


}

