
import java_swift
import javax_swing
import java_lang
import java_awt

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home ///
/// Tue Dec 20 11:52:08 GMT 2016 ///

/// class com.apple.laf.AquaTableHeaderBorder ///

open class AquaTableHeaderBorder: javax_swing.AbstractBorder {

    public convenience init?( casting object: java_lang.JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        if !object.validDownCast( toJavaClass: "com.apple.laf.AquaTableHeaderBorder", file, line ) {
            return nil
        }
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var AquaTableHeaderBorderJNIClass: jclass?

    /// protected static final int com.apple.laf.AquaTableHeaderBorder.SORT_NONE

    /// protected static final int com.apple.laf.AquaTableHeaderBorder.SORT_ASCENDING

    /// protected static final int com.apple.laf.AquaTableHeaderBorder.SORT_DECENDING

    /// protected final java.awt.Insets com.apple.laf.AquaTableHeaderBorder.editorBorderInsets

    private static var editorBorderInsets_FieldID: jfieldID?

    open var editorBorderInsets: java_awt.Insets! {
        get {
            var __locals = [jobject]()
            let __value = JNIField.GetObjectField( fieldName: "editorBorderInsets", fieldType: "Ljava/awt/Insets;", fieldCache: &AquaTableHeaderBorder.editorBorderInsets_FieldID, object: javaObject, locals: &__locals )
            return __value != nil ? java_awt.Insets( javaObject: __value ) : nil
        }
    }

    /// protected final com.apple.laf.AquaPainter com.apple.laf.AquaTableHeaderBorder.painter

    private static var painter_FieldID: jfieldID?

    open var painter: /* com.apple.laf.AquaPainter */ UnclassedObject! {
        get {
            var __locals = [jobject]()
            let __value = JNIField.GetObjectField( fieldName: "painter", fieldType: "Lcom/apple/laf/AquaPainter;", fieldCache: &AquaTableHeaderBorder.painter_FieldID, object: javaObject, locals: &__locals )
            return __value != nil ? /* com.apple.laf.AquaPainter */ UnclassedObject( javaObject: __value ) : nil
        }
    }

    /// protected boolean com.apple.laf.AquaTableHeaderBorder.doPaint

    private static var doPaint_FieldID: jfieldID?

    open var doPaint: Bool {
        get {
            var __locals = [jobject]()
            let __value = JNIField.GetBooleanField( fieldName: "doPaint", fieldType: "Z", fieldCache: &AquaTableHeaderBorder.doPaint_FieldID, object: javaObject, locals: &__locals )
            return JNIType.decode( type: Bool(), from: __value )
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.encode( value: newValue, locals: &__locals )
            JNIField.SetBooleanField( fieldName: "doPaint", fieldType: "Z", fieldCache: &AquaTableHeaderBorder.doPaint_FieldID, object: javaObject, value: __value.z, locals: &__locals )
        }
    }

    /// static final com.apple.laf.AquaUtils$LazySingleton com.apple.laf.AquaTableHeaderBorder.alternateBorder

    /// private boolean com.apple.laf.AquaTableHeaderBorder.selected

    /// private int com.apple.laf.AquaTableHeaderBorder.fHorizontalShift

    /// private int com.apple.laf.AquaTableHeaderBorder.sortOrder

    /// protected com.apple.laf.AquaTableHeaderBorder()

    private static var new_MethodID_1: jmethodID?

    public convenience init() {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __object = JNIMethod.NewObject( className: "com/apple/laf/AquaTableHeaderBorder", classCache: &AquaTableHeaderBorder.AquaTableHeaderBorderJNIClass, methodSig: "()V", methodCache: &AquaTableHeaderBorder.new_MethodID_1, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    /// protected apple.laf.JRSUIConstants$State com.apple.laf.AquaTableHeaderBorder.getState(javax.swing.JComponent)

    private static var getState_MethodID_2: jmethodID?

    open func getState( arg0: javax_swing.JComponent? ) -> /* apple.laf.JRSUIConstants$State */ UnclassedObject! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getState", methodSig: "(Ljavax/swing/JComponent;)Lapple/laf/JRSUIConstants$State;", methodCache: &AquaTableHeaderBorder.getState_MethodID_2, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? /* apple.laf.JRSUIConstants$State */ UnclassedObject( javaObject: __return ) : nil
    }

    open func getState( _ _arg0: javax_swing.JComponent? ) -> /* apple.laf.JRSUIConstants$State */ UnclassedObject! {
        return getState( arg0: _arg0 )
    }

    /// public void com.apple.laf.AquaTableHeaderBorder.paintBorder(java.awt.Component,java.awt.Graphics,int,int,int,int)

    /// public java.awt.Insets com.apple.laf.AquaTableHeaderBorder.getBorderInsets(java.awt.Component,java.awt.Insets)

    /// public java.awt.Insets com.apple.laf.AquaTableHeaderBorder.getBorderInsets(java.awt.Component)

    /// public boolean com.apple.laf.AquaTableHeaderBorder.isBorderOpaque()

    /// protected void com.apple.laf.AquaTableHeaderBorder.setSelected(boolean)

    private static var setSelected_MethodID_3: jmethodID?

    open func setSelected( arg0: Bool ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "setSelected", methodSig: "(Z)V", methodCache: &AquaTableHeaderBorder.setSelected_MethodID_3, args: &__args, locals: &__locals )
    }

    open func setSelected( _ _arg0: Bool ) {
        setSelected( arg0: _arg0 )
    }

    /// protected static com.apple.laf.AquaTableHeaderBorder com.apple.laf.AquaTableHeaderBorder.getListHeaderBorder()

    private static var getListHeaderBorder_MethodID_4: jmethodID?

    open class func getListHeaderBorder() -> AquaTableHeaderBorder! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaTableHeaderBorder", classCache: &AquaTableHeaderBorderJNIClass, methodName: "getListHeaderBorder", methodSig: "()Lcom/apple/laf/AquaTableHeaderBorder;", methodCache: &getListHeaderBorder_MethodID_4, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? AquaTableHeaderBorder( javaObject: __return ) : nil
    }


    /// protected void com.apple.laf.AquaTableHeaderBorder.setHorizontalShift(int)

    private static var setHorizontalShift_MethodID_5: jmethodID?

    open func setHorizontalShift( arg0: Int ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "setHorizontalShift", methodSig: "(I)V", methodCache: &AquaTableHeaderBorder.setHorizontalShift_MethodID_5, args: &__args, locals: &__locals )
    }

    open func setHorizontalShift( _ _arg0: Int ) {
        setHorizontalShift( arg0: _arg0 )
    }

    /// protected void com.apple.laf.AquaTableHeaderBorder.setSortOrder(int)

    private static var setSortOrder_MethodID_6: jmethodID?

    open func setSortOrder( arg0: Int ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "setSortOrder", methodSig: "(I)V", methodCache: &AquaTableHeaderBorder.setSortOrder_MethodID_6, args: &__args, locals: &__locals )
    }

    open func setSortOrder( _ _arg0: Int ) {
        setSortOrder( arg0: _arg0 )
    }

    /// protected static javax.swing.border.Border com.apple.laf.AquaTableHeaderBorder.getAlternateBorder()

    private static var getAlternateBorder_MethodID_7: jmethodID?

    open class func getAlternateBorder() -> javax_swing.Border! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaTableHeaderBorder", classCache: &AquaTableHeaderBorderJNIClass, methodName: "getAlternateBorder", methodSig: "()Ljavax/swing/border/Border;", methodCache: &getAlternateBorder_MethodID_7, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? javax_swing.BorderForward( javaObject: __return ) : nil
    }


}
