
import java_swift
import java_awt
import java_util
import javax_swing

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home ///
/// Fri Aug 04 11:17:08 BST 2017 ///

/// class com.apple.laf.AquaFocusHandler ///

open class AquaFocusHandler: java_swift.JavaObject, java_awt.FocusListener, /* java.beans.PropertyChangeListener */ UnclassedProtocol {

    public convenience init?( casting object: java_swift.JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var AquaFocusHandlerJNIClass: jclass?

    /// private boolean com.apple.laf.AquaFocusHandler.wasTemporary

    /// private boolean com.apple.laf.AquaFocusHandler.repaintBorder

    /// protected static final java.lang.String com.apple.laf.AquaFocusHandler.FRAME_ACTIVE_PROPERTY

    /// static final java.beans.PropertyChangeListener com.apple.laf.AquaFocusHandler.REPAINT_LISTENER

    /// public com.apple.laf.AquaFocusHandler()

    private static var new_MethodID_1: jmethodID?

    public convenience init() {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __object = JNIMethod.NewObject( className: "com/apple/laf/AquaFocusHandler", classCache: &AquaFocusHandler.AquaFocusHandlerJNIClass, methodSig: "()V", methodCache: &AquaFocusHandler.new_MethodID_1, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    /// static void com.apple.laf.AquaFocusHandler.swapSelectionColors(java.lang.String,javax.swing.JList,java.lang.Object)

    /// static void com.apple.laf.AquaFocusHandler.swapSelectionColors(java.lang.String,javax.swing.JTree,java.lang.Object)

    /// static void com.apple.laf.AquaFocusHandler.swapSelectionColors(java.lang.String,javax.swing.JTable,java.lang.Object)

    /// static void com.apple.laf.AquaFocusHandler.setSelectionColors(javax.swing.JList,java.lang.String,java.lang.String)

    /// static void com.apple.laf.AquaFocusHandler.setSelectionColors(javax.swing.JTable,java.lang.String,java.lang.String)

    /// static boolean com.apple.laf.AquaFocusHandler.isComponentValid(javax.swing.JComponent)

    /// protected static void com.apple.laf.AquaFocusHandler.install(javax.swing.JComponent)

    private static var install_MethodID_2: jmethodID?

    open class func install( arg0: javax_swing.JComponent? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: arg0 != nil ? arg0! as JNIObject : nil, locals: &__locals )
        JNIMethod.CallStaticVoidMethod( className: "com/apple/laf/AquaFocusHandler", classCache: &AquaFocusHandlerJNIClass, methodName: "install", methodSig: "(Ljavax/swing/JComponent;)V", methodCache: &install_MethodID_2, args: &__args, locals: &__locals )
    }

    open class func install( _ _arg0: javax_swing.JComponent? ) {
        install( arg0: _arg0 )
    }

    /// protected static void com.apple.laf.AquaFocusHandler.uninstall(javax.swing.JComponent)

    private static var uninstall_MethodID_3: jmethodID?

    open class func uninstall( arg0: javax_swing.JComponent? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: arg0 != nil ? arg0! as JNIObject : nil, locals: &__locals )
        JNIMethod.CallStaticVoidMethod( className: "com/apple/laf/AquaFocusHandler", classCache: &AquaFocusHandlerJNIClass, methodName: "uninstall", methodSig: "(Ljavax/swing/JComponent;)V", methodCache: &uninstall_MethodID_3, args: &__args, locals: &__locals )
    }

    open class func uninstall( _ _arg0: javax_swing.JComponent? ) {
        uninstall( arg0: _arg0 )
    }

    /// public void com.apple.laf.AquaFocusHandler.propertyChange(java.beans.PropertyChangeEvent)

    private static var propertyChange_MethodID_4: jmethodID?

    open func propertyChange( evt: /* java.beans.PropertyChangeEvent */ UnclassedObject? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: evt != nil ? evt! as JNIObject : nil, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "propertyChange", methodSig: "(Ljava/beans/PropertyChangeEvent;)V", methodCache: &AquaFocusHandler.propertyChange_MethodID_4, args: &__args, locals: &__locals )
    }

    open func propertyChange( _ _evt: /* java.beans.PropertyChangeEvent */ UnclassedObject? ) {
        propertyChange( evt: _evt )
    }

    /// public void com.apple.laf.AquaFocusHandler.focusGained(java.awt.event.FocusEvent)

    private static var focusGained_MethodID_5: jmethodID?

    open func focusGained( e: java_awt.FocusEvent? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: e != nil ? e! as JNIObject : nil, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "focusGained", methodSig: "(Ljava/awt/event/FocusEvent;)V", methodCache: &AquaFocusHandler.focusGained_MethodID_5, args: &__args, locals: &__locals )
    }

    open func focusGained( _ _e: java_awt.FocusEvent? ) {
        focusGained( e: _e )
    }

    /// public void com.apple.laf.AquaFocusHandler.focusLost(java.awt.event.FocusEvent)

    private static var focusLost_MethodID_6: jmethodID?

    open func focusLost( e: java_awt.FocusEvent? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: e != nil ? e! as JNIObject : nil, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "focusLost", methodSig: "(Ljava/awt/event/FocusEvent;)V", methodCache: &AquaFocusHandler.focusLost_MethodID_6, args: &__args, locals: &__locals )
    }

    open func focusLost( _ _e: java_awt.FocusEvent? ) {
        focusLost( e: _e )
    }

    /// protected static boolean com.apple.laf.AquaFocusHandler.isActive(javax.swing.JComponent)

    private static var isActive_MethodID_7: jmethodID?

    open class func isActive( arg0: javax_swing.JComponent? ) -> Bool {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: arg0 != nil ? arg0! as JNIObject : nil, locals: &__locals )
        let __return = JNIMethod.CallStaticBooleanMethod( className: "com/apple/laf/AquaFocusHandler", classCache: &AquaFocusHandlerJNIClass, methodName: "isActive", methodSig: "(Ljavax/swing/JComponent;)Z", methodCache: &isActive_MethodID_7, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: Bool(), from: __return )
    }

    open class func isActive( _ _arg0: javax_swing.JComponent? ) -> Bool {
        return isActive( arg0: _arg0 )
    }

}

