
import java_swift
import java_awt

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home ///
/// Tue Aug 08 14:27:28 BST 2017 ///

/// class com.apple.laf.AquaNativeResources ///

open class AquaNativeResources: java_swift.JavaObject {

    public convenience init?( casting object: java_swift.JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var AquaNativeResourcesJNIClass: jclass?

    /// static final com.apple.laf.AquaUtils$RecyclableSingleton com.apple.laf.AquaNativeResources.sBackgroundColor

    /// public com.apple.laf.AquaNativeResources()

    private static var new_MethodID_1: jmethodID?

    public convenience init() {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __object = JNIMethod.NewObject( className: "com/apple/laf/AquaNativeResources", classCache: &AquaNativeResources.AquaNativeResourcesJNIClass, methodSig: "()V", methodCache: &AquaNativeResources.new_MethodID_1, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    /// static long com.apple.laf.AquaNativeResources.access$000()

    /// private static native long com.apple.laf.AquaNativeResources.getWindowBackgroundColor()

    /// public static java.awt.Color com.apple.laf.AquaNativeResources.getWindowBackgroundColorUIResource()

    private static var getWindowBackgroundColorUIResource_MethodID_2: jmethodID?

    open class func getWindowBackgroundColorUIResource() -> java_awt.Color! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaNativeResources", classCache: &AquaNativeResourcesJNIClass, methodName: "getWindowBackgroundColorUIResource", methodSig: "()Ljava/awt/Color;", methodCache: &getWindowBackgroundColorUIResource_MethodID_2, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_awt.Color( javaObject: __return ) : nil
    }


    /// static java.awt.image.BufferedImage com.apple.laf.AquaNativeResources.getRadioButtonSizerImage()

}

