
import java_swift
import javax_swing
import java_awt

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// class com.apple.laf.AquaInternalFrameUI ///

open class AquaInternalFrameUI: javax_swing.BasicInternalFrameUI, javax_swing.SwingConstants {

    public convenience init?( casting object: java_swift.JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var AquaInternalFrameUIJNIClass: jclass?

    /// private static final java.lang.String com.apple.laf.AquaInternalFrameUI.FRAME_TYPE

    /// protected static final java.lang.String com.apple.laf.AquaInternalFrameUI.IS_PALETTE_PROPERTY

    // Skipping field: false false false false false true 

    /// private static final java.lang.String com.apple.laf.AquaInternalFrameUI.NORMAL_FRAME

    /// private static final java.lang.String com.apple.laf.AquaInternalFrameUI.OPTION_DIALOG

    /// private static final java.lang.String com.apple.laf.AquaInternalFrameUI.PALETTE_FRAME

    /// static final com.apple.laf.AquaUtils$RecyclableSingleton com.apple.laf.AquaInternalFrameUI.RESIZE_ICON

    // Skipping field: true false false false false false 

    /// static final com.apple.laf.AquaUtils$RecyclableSingleton com.apple.laf.AquaInternalFrameUI.closeIcon

    // Skipping field: true false false false false false 

    /// static final com.apple.laf.AquaInternalFrameUI$InternalFrameShadow com.apple.laf.AquaInternalFrameUI.documentWindowShadow

    // Skipping field: true false false false false false 

    /// static final com.apple.laf.AquaUtils$RecyclableSingleton com.apple.laf.AquaInternalFrameUI.minimizeIcon

    // Skipping field: true false false false false false 

    /// static final com.apple.laf.AquaInternalFrameUI$InternalFrameShadow com.apple.laf.AquaInternalFrameUI.paletteWindowShadow

    // Skipping field: true false false false false false 

    /// static final com.apple.laf.AquaUtils$RecyclableSingleton com.apple.laf.AquaInternalFrameUI.zoomIcon

    // Skipping field: true false false false false false 

    /// com.apple.laf.AquaInternalFrameBorder com.apple.laf.AquaInternalFrameUI.fAquaBorder

    // Skipping field: true false false false false false 

    /// boolean com.apple.laf.AquaInternalFrameUI.fDocumentEdited

    // Skipping field: true false false false false false 

    /// boolean com.apple.laf.AquaInternalFrameUI.fIsPallet

    // Skipping field: true false false false false false 

    /// boolean com.apple.laf.AquaInternalFrameUI.fMouseOverPressedButton

    // Skipping field: true false false false false false 

    /// protected java.awt.Color com.apple.laf.AquaInternalFrameUI.fNotSelectedTextColor

    private static var fNotSelectedTextColor_FieldID: jfieldID?

    open var fNotSelectedTextColor: java_awt.Color! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "fNotSelectedTextColor", fieldType: "Ljava/awt/Color;", fieldCache: &AquaInternalFrameUI.fNotSelectedTextColor_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? java_awt.Color( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "fNotSelectedTextColor", fieldType: "Ljava/awt/Color;", fieldCache: &AquaInternalFrameUI.fNotSelectedTextColor_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// java.beans.PropertyChangeListener com.apple.laf.AquaInternalFrameUI.fPropertyListener

    // Skipping field: true false false false false false 

    /// boolean com.apple.laf.AquaInternalFrameUI.fRollover

    // Skipping field: true false false false false false 

    /// protected java.awt.Color com.apple.laf.AquaInternalFrameUI.fSelectedTextColor

    private static var fSelectedTextColor_FieldID: jfieldID?

    open var fSelectedTextColor: java_awt.Color! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "fSelectedTextColor", fieldType: "Ljava/awt/Color;", fieldCache: &AquaInternalFrameUI.fSelectedTextColor_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? java_awt.Color( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "fSelectedTextColor", fieldType: "Ljava/awt/Color;", fieldCache: &AquaInternalFrameUI.fSelectedTextColor_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// int com.apple.laf.AquaInternalFrameUI.fWhichButtonPressed

    // Skipping field: true false false false false false 

    /// protected com.apple.laf.AquaInternalFrameUI$ResizeBox com.apple.laf.AquaInternalFrameUI.resizeBox

    private static var resizeBox_FieldID: jfieldID?

    open var resizeBox: /* class com.apple.laf.AquaInternalFrameUI$ResizeBox */ UnavailableObject! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "resizeBox", fieldType: "Lcom/apple/laf/AquaInternalFrameUI$ResizeBox;", fieldCache: &AquaInternalFrameUI.resizeBox_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? /* class com.apple.laf.AquaInternalFrameUI$ResizeBox */ UnavailableObject( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "resizeBox", fieldType: "Lcom/apple/laf/AquaInternalFrameUI$ResizeBox;", fieldCache: &AquaInternalFrameUI.resizeBox_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// private static javax.swing.DesktopManager javax.swing.plaf.basic.BasicInternalFrameUI.sharedDesktopManager

    /// protected javax.swing.event.MouseInputAdapter javax.swing.plaf.basic.BasicInternalFrameUI.borderListener

    private static var borderListener_FieldID: jfieldID?

    override open var borderListener: javax_swing.MouseInputAdapter! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "borderListener", fieldType: "Ljavax/swing/event/MouseInputAdapter;", fieldCache: &AquaInternalFrameUI.borderListener_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? javax_swing.MouseInputAdapter( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "borderListener", fieldType: "Ljavax/swing/event/MouseInputAdapter;", fieldCache: &AquaInternalFrameUI.borderListener_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// protected java.awt.event.ComponentListener javax.swing.plaf.basic.BasicInternalFrameUI.componentListener

    private static var componentListener_FieldID: jfieldID?

    override open var componentListener: java_awt.ComponentListener! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "componentListener", fieldType: "Ljava/awt/event/ComponentListener;", fieldCache: &AquaInternalFrameUI.componentListener_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? java_awt.ComponentListenerForward( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "componentListener", fieldType: "Ljava/awt/event/ComponentListener;", fieldCache: &AquaInternalFrameUI.componentListener_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// private boolean javax.swing.plaf.basic.BasicInternalFrameUI.componentListenerAdded

    /// private boolean javax.swing.plaf.basic.BasicInternalFrameUI.dragging

    /// protected javax.swing.JComponent javax.swing.plaf.basic.BasicInternalFrameUI.eastPane

    private static var eastPane_FieldID: jfieldID?

    override open var eastPane: javax_swing.JComponent! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "eastPane", fieldType: "Ljavax/swing/JComponent;", fieldCache: &AquaInternalFrameUI.eastPane_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? javax_swing.JComponent( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "eastPane", fieldType: "Ljavax/swing/JComponent;", fieldCache: &AquaInternalFrameUI.eastPane_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// protected javax.swing.JInternalFrame javax.swing.plaf.basic.BasicInternalFrameUI.frame

    private static var frame_FieldID: jfieldID?

    override open var frame: javax_swing.JInternalFrame! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "frame", fieldType: "Ljavax/swing/JInternalFrame;", fieldCache: &AquaInternalFrameUI.frame_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? javax_swing.JInternalFrame( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "frame", fieldType: "Ljavax/swing/JInternalFrame;", fieldCache: &AquaInternalFrameUI.frame_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// protected javax.swing.event.MouseInputListener javax.swing.plaf.basic.BasicInternalFrameUI.glassPaneDispatcher

    private static var glassPaneDispatcher_FieldID: jfieldID?

    override open var glassPaneDispatcher: javax_swing.MouseInputListener! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "glassPaneDispatcher", fieldType: "Ljavax/swing/event/MouseInputListener;", fieldCache: &AquaInternalFrameUI.glassPaneDispatcher_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? javax_swing.MouseInputListenerForward( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "glassPaneDispatcher", fieldType: "Ljavax/swing/event/MouseInputListener;", fieldCache: &AquaInternalFrameUI.glassPaneDispatcher_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// private javax.swing.plaf.basic.BasicInternalFrameUI$Handler javax.swing.plaf.basic.BasicInternalFrameUI.handler

    /// protected java.awt.LayoutManager javax.swing.plaf.basic.BasicInternalFrameUI.internalFrameLayout

    private static var internalFrameLayout_FieldID: jfieldID?

    override open var internalFrameLayout: java_awt.LayoutManager! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "internalFrameLayout", fieldType: "Ljava/awt/LayoutManager;", fieldCache: &AquaInternalFrameUI.internalFrameLayout_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? java_awt.LayoutManagerForward( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "internalFrameLayout", fieldType: "Ljava/awt/LayoutManager;", fieldCache: &AquaInternalFrameUI.internalFrameLayout_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// private javax.swing.event.InternalFrameListener javax.swing.plaf.basic.BasicInternalFrameUI.internalFrameListener

    /// private boolean javax.swing.plaf.basic.BasicInternalFrameUI.keyBindingActive

    /// private boolean javax.swing.plaf.basic.BasicInternalFrameUI.keyBindingRegistered

    /// protected javax.swing.JComponent javax.swing.plaf.basic.BasicInternalFrameUI.northPane

    private static var northPane_FieldID: jfieldID?

    override open var northPane: javax_swing.JComponent! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "northPane", fieldType: "Ljavax/swing/JComponent;", fieldCache: &AquaInternalFrameUI.northPane_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? javax_swing.JComponent( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "northPane", fieldType: "Ljavax/swing/JComponent;", fieldCache: &AquaInternalFrameUI.northPane_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// protected javax.swing.KeyStroke javax.swing.plaf.basic.BasicInternalFrameUI.openMenuKey

    private static var openMenuKey_FieldID: jfieldID?

    override open var openMenuKey: javax_swing.KeyStroke! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "openMenuKey", fieldType: "Ljavax/swing/KeyStroke;", fieldCache: &AquaInternalFrameUI.openMenuKey_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? javax_swing.KeyStroke( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "openMenuKey", fieldType: "Ljavax/swing/KeyStroke;", fieldCache: &AquaInternalFrameUI.openMenuKey_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// private java.awt.Rectangle javax.swing.plaf.basic.BasicInternalFrameUI.parentBounds

    /// protected java.beans.PropertyChangeListener javax.swing.plaf.basic.BasicInternalFrameUI.propertyChangeListener

    private static var propertyChangeListener_FieldID: jfieldID?

    override open var propertyChangeListener: /* interface java.beans.PropertyChangeListener */ UnavailableProtocol! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "propertyChangeListener", fieldType: "Ljava/beans/PropertyChangeListener;", fieldCache: &AquaInternalFrameUI.propertyChangeListener_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? /* interface java.beans.PropertyChangeListener */ UnavailableProtocolForward( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "propertyChangeListener", fieldType: "Ljava/beans/PropertyChangeListener;", fieldCache: &AquaInternalFrameUI.propertyChangeListener_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// private boolean javax.swing.plaf.basic.BasicInternalFrameUI.resizing

    /// protected javax.swing.JComponent javax.swing.plaf.basic.BasicInternalFrameUI.southPane

    private static var southPane_FieldID: jfieldID?

    override open var southPane: javax_swing.JComponent! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "southPane", fieldType: "Ljavax/swing/JComponent;", fieldCache: &AquaInternalFrameUI.southPane_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? javax_swing.JComponent( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "southPane", fieldType: "Ljavax/swing/JComponent;", fieldCache: &AquaInternalFrameUI.southPane_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// protected javax.swing.plaf.basic.BasicInternalFrameTitlePane javax.swing.plaf.basic.BasicInternalFrameUI.titlePane

    private static var titlePane_FieldID: jfieldID?

    override open var titlePane: javax_swing.BasicInternalFrameTitlePane! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "titlePane", fieldType: "Ljavax/swing/plaf/basic/BasicInternalFrameTitlePane;", fieldCache: &AquaInternalFrameUI.titlePane_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? javax_swing.BasicInternalFrameTitlePane( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "titlePane", fieldType: "Ljavax/swing/plaf/basic/BasicInternalFrameTitlePane;", fieldCache: &AquaInternalFrameUI.titlePane_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// protected javax.swing.JComponent javax.swing.plaf.basic.BasicInternalFrameUI.westPane

    private static var westPane_FieldID: jfieldID?

    override open var westPane: javax_swing.JComponent! {
        get {
            let __value = JNIField.GetObjectField( fieldName: "westPane", fieldType: "Ljavax/swing/JComponent;", fieldCache: &AquaInternalFrameUI.westPane_FieldID, object: javaObject )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? javax_swing.JComponent( javaObject: __value ) : nil
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "westPane", fieldType: "Ljavax/swing/JComponent;", fieldCache: &AquaInternalFrameUI.westPane_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// public static final int javax.swing.SwingConstants.BOTTOM

    private static var BOTTOM_FieldID: jfieldID?

    public static var BOTTOM: Int {
        get {
            let __value = JNIField.GetStaticIntField( fieldName: "BOTTOM", fieldType: "I", fieldCache: &BOTTOM_FieldID, className: "com/apple/laf/AquaInternalFrameUI", classCache: &AquaInternalFrameUIJNIClass )
            return Int(__value)
        }
    }

    /// public static final int javax.swing.SwingConstants.CENTER

    private static var CENTER_FieldID: jfieldID?

    public static var CENTER: Int {
        get {
            let __value = JNIField.GetStaticIntField( fieldName: "CENTER", fieldType: "I", fieldCache: &CENTER_FieldID, className: "com/apple/laf/AquaInternalFrameUI", classCache: &AquaInternalFrameUIJNIClass )
            return Int(__value)
        }
    }

    /// public static final int javax.swing.SwingConstants.EAST

    private static var EAST_FieldID: jfieldID?

    public static var EAST: Int {
        get {
            let __value = JNIField.GetStaticIntField( fieldName: "EAST", fieldType: "I", fieldCache: &EAST_FieldID, className: "com/apple/laf/AquaInternalFrameUI", classCache: &AquaInternalFrameUIJNIClass )
            return Int(__value)
        }
    }

    /// public static final int javax.swing.SwingConstants.HORIZONTAL

    private static var HORIZONTAL_FieldID: jfieldID?

    public static var HORIZONTAL: Int {
        get {
            let __value = JNIField.GetStaticIntField( fieldName: "HORIZONTAL", fieldType: "I", fieldCache: &HORIZONTAL_FieldID, className: "com/apple/laf/AquaInternalFrameUI", classCache: &AquaInternalFrameUIJNIClass )
            return Int(__value)
        }
    }

    /// public static final int javax.swing.SwingConstants.LEADING

    private static var LEADING_FieldID: jfieldID?

    public static var LEADING: Int {
        get {
            let __value = JNIField.GetStaticIntField( fieldName: "LEADING", fieldType: "I", fieldCache: &LEADING_FieldID, className: "com/apple/laf/AquaInternalFrameUI", classCache: &AquaInternalFrameUIJNIClass )
            return Int(__value)
        }
    }

    /// public static final int javax.swing.SwingConstants.LEFT

    private static var LEFT_FieldID: jfieldID?

    public static var LEFT: Int {
        get {
            let __value = JNIField.GetStaticIntField( fieldName: "LEFT", fieldType: "I", fieldCache: &LEFT_FieldID, className: "com/apple/laf/AquaInternalFrameUI", classCache: &AquaInternalFrameUIJNIClass )
            return Int(__value)
        }
    }

    /// public static final int javax.swing.SwingConstants.NEXT

    private static var NEXT_FieldID: jfieldID?

    public static var NEXT: Int {
        get {
            let __value = JNIField.GetStaticIntField( fieldName: "NEXT", fieldType: "I", fieldCache: &NEXT_FieldID, className: "com/apple/laf/AquaInternalFrameUI", classCache: &AquaInternalFrameUIJNIClass )
            return Int(__value)
        }
    }

    /// public static final int javax.swing.SwingConstants.NORTH

    private static var NORTH_FieldID: jfieldID?

    public static var NORTH: Int {
        get {
            let __value = JNIField.GetStaticIntField( fieldName: "NORTH", fieldType: "I", fieldCache: &NORTH_FieldID, className: "com/apple/laf/AquaInternalFrameUI", classCache: &AquaInternalFrameUIJNIClass )
            return Int(__value)
        }
    }

    /// public static final int javax.swing.SwingConstants.NORTH_EAST

    private static var NORTH_EAST_FieldID: jfieldID?

    public static var NORTH_EAST: Int {
        get {
            let __value = JNIField.GetStaticIntField( fieldName: "NORTH_EAST", fieldType: "I", fieldCache: &NORTH_EAST_FieldID, className: "com/apple/laf/AquaInternalFrameUI", classCache: &AquaInternalFrameUIJNIClass )
            return Int(__value)
        }
    }

    /// public static final int javax.swing.SwingConstants.NORTH_WEST

    private static var NORTH_WEST_FieldID: jfieldID?

    public static var NORTH_WEST: Int {
        get {
            let __value = JNIField.GetStaticIntField( fieldName: "NORTH_WEST", fieldType: "I", fieldCache: &NORTH_WEST_FieldID, className: "com/apple/laf/AquaInternalFrameUI", classCache: &AquaInternalFrameUIJNIClass )
            return Int(__value)
        }
    }

    /// public static final int javax.swing.SwingConstants.PREVIOUS

    private static var PREVIOUS_FieldID: jfieldID?

    public static var PREVIOUS: Int {
        get {
            let __value = JNIField.GetStaticIntField( fieldName: "PREVIOUS", fieldType: "I", fieldCache: &PREVIOUS_FieldID, className: "com/apple/laf/AquaInternalFrameUI", classCache: &AquaInternalFrameUIJNIClass )
            return Int(__value)
        }
    }

    /// public static final int javax.swing.SwingConstants.RIGHT

    private static var RIGHT_FieldID: jfieldID?

    public static var RIGHT: Int {
        get {
            let __value = JNIField.GetStaticIntField( fieldName: "RIGHT", fieldType: "I", fieldCache: &RIGHT_FieldID, className: "com/apple/laf/AquaInternalFrameUI", classCache: &AquaInternalFrameUIJNIClass )
            return Int(__value)
        }
    }

    /// public static final int javax.swing.SwingConstants.SOUTH

    private static var SOUTH_FieldID: jfieldID?

    public static var SOUTH: Int {
        get {
            let __value = JNIField.GetStaticIntField( fieldName: "SOUTH", fieldType: "I", fieldCache: &SOUTH_FieldID, className: "com/apple/laf/AquaInternalFrameUI", classCache: &AquaInternalFrameUIJNIClass )
            return Int(__value)
        }
    }

    /// public static final int javax.swing.SwingConstants.SOUTH_EAST

    private static var SOUTH_EAST_FieldID: jfieldID?

    public static var SOUTH_EAST: Int {
        get {
            let __value = JNIField.GetStaticIntField( fieldName: "SOUTH_EAST", fieldType: "I", fieldCache: &SOUTH_EAST_FieldID, className: "com/apple/laf/AquaInternalFrameUI", classCache: &AquaInternalFrameUIJNIClass )
            return Int(__value)
        }
    }

    /// public static final int javax.swing.SwingConstants.SOUTH_WEST

    private static var SOUTH_WEST_FieldID: jfieldID?

    public static var SOUTH_WEST: Int {
        get {
            let __value = JNIField.GetStaticIntField( fieldName: "SOUTH_WEST", fieldType: "I", fieldCache: &SOUTH_WEST_FieldID, className: "com/apple/laf/AquaInternalFrameUI", classCache: &AquaInternalFrameUIJNIClass )
            return Int(__value)
        }
    }

    /// public static final int javax.swing.SwingConstants.TOP

    private static var TOP_FieldID: jfieldID?

    public static var TOP: Int {
        get {
            let __value = JNIField.GetStaticIntField( fieldName: "TOP", fieldType: "I", fieldCache: &TOP_FieldID, className: "com/apple/laf/AquaInternalFrameUI", classCache: &AquaInternalFrameUIJNIClass )
            return Int(__value)
        }
    }

    /// public static final int javax.swing.SwingConstants.TRAILING

    private static var TRAILING_FieldID: jfieldID?

    public static var TRAILING: Int {
        get {
            let __value = JNIField.GetStaticIntField( fieldName: "TRAILING", fieldType: "I", fieldCache: &TRAILING_FieldID, className: "com/apple/laf/AquaInternalFrameUI", classCache: &AquaInternalFrameUIJNIClass )
            return Int(__value)
        }
    }

    /// public static final int javax.swing.SwingConstants.VERTICAL

    private static var VERTICAL_FieldID: jfieldID?

    public static var VERTICAL: Int {
        get {
            let __value = JNIField.GetStaticIntField( fieldName: "VERTICAL", fieldType: "I", fieldCache: &VERTICAL_FieldID, className: "com/apple/laf/AquaInternalFrameUI", classCache: &AquaInternalFrameUIJNIClass )
            return Int(__value)
        }
    }

    /// public static final int javax.swing.SwingConstants.WEST

    private static var WEST_FieldID: jfieldID?

    public static var WEST: Int {
        get {
            let __value = JNIField.GetStaticIntField( fieldName: "WEST", fieldType: "I", fieldCache: &WEST_FieldID, className: "com/apple/laf/AquaInternalFrameUI", classCache: &AquaInternalFrameUIJNIClass )
            return Int(__value)
        }
    }

    /// public com.apple.laf.AquaInternalFrameUI(javax.swing.JInternalFrame)

    private static var new_MethodID_1: jmethodID?

    public convenience init( arg0: javax_swing.JInternalFrame? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "com/apple/laf/AquaInternalFrameUI", classCache: &AquaInternalFrameUI.AquaInternalFrameUIJNIClass, methodSig: "(Ljavax/swing/JInternalFrame;)V", methodCache: &AquaInternalFrameUI.new_MethodID_1, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _arg0: javax_swing.JInternalFrame? ) {
        self.init( arg0: _arg0 )
    }

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$000(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$100(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$1000(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$1100(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.DesktopManager com.apple.laf.AquaInternalFrameUI.access$1200(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$1300(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$1400(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$1500(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$1600(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.DesktopManager com.apple.laf.AquaInternalFrameUI.access$1700(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$1800(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$1900(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$200(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$2000(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$2100(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.DesktopManager com.apple.laf.AquaInternalFrameUI.access$2200(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$2300(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.DesktopManager com.apple.laf.AquaInternalFrameUI.access$2400(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$2500(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$2600(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$2700(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$2800(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$2900(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$300(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$3000(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$3100(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$3200(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$3300(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$3400(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.DesktopManager com.apple.laf.AquaInternalFrameUI.access$3500(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$3600(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$3700(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$3800(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$3900(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$400(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$4000(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$4100(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$4200(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$4300(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$4400(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$4500(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$4600(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$4700(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$4800(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$4900(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$500(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$5000(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$5100(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$5200(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$5300(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$5400(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$5500(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$5600(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$5700(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$5800(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$5900(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$600(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$6000(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$6100(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$6200(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$6300(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$6400(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.DesktopManager com.apple.laf.AquaInternalFrameUI.access$6500(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$6600(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$6700(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$6800(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$6900(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$700(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$7000(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$7100(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$7200(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$7300(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.DesktopManager com.apple.laf.AquaInternalFrameUI.access$7400(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$7500(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.DesktopManager com.apple.laf.AquaInternalFrameUI.access$7600(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$800(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// static javax.swing.JInternalFrame com.apple.laf.AquaInternalFrameUI.access$900(com.apple.laf.AquaInternalFrameUI)

    // Skipping method: true false false false false 

    /// public static javax.swing.plaf.ComponentUI com.apple.laf.AquaInternalFrameUI.createUI(javax.swing.JComponent)

    private static var createUI_MethodID_2: jmethodID?

    open class func createUI( arg0: javax_swing.JComponent? ) -> javax_swing.ComponentUI! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaInternalFrameUI", classCache: &AquaInternalFrameUIJNIClass, methodName: "createUI", methodSig: "(Ljavax/swing/JComponent;)Ljavax/swing/plaf/ComponentUI;", methodCache: &createUI_MethodID_2, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? javax_swing.ComponentUI( javaObject: __return ) : nil
    }

    override open class func createUI( _ _arg0: javax_swing.JComponent? ) -> javax_swing.ComponentUI! {
        return createUI( arg0: _arg0 )
    }

    /// public static javax.swing.Icon com.apple.laf.AquaInternalFrameUI.exportCloseIcon()

    private static var exportCloseIcon_MethodID_3: jmethodID?

    open class func exportCloseIcon() -> javax_swing.Icon! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaInternalFrameUI", classCache: &AquaInternalFrameUIJNIClass, methodName: "exportCloseIcon", methodSig: "()Ljavax/swing/Icon;", methodCache: &exportCloseIcon_MethodID_3, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? javax_swing.IconForward( javaObject: __return ) : nil
    }


    /// public static javax.swing.Icon com.apple.laf.AquaInternalFrameUI.exportMinimizeIcon()

    private static var exportMinimizeIcon_MethodID_4: jmethodID?

    open class func exportMinimizeIcon() -> javax_swing.Icon! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaInternalFrameUI", classCache: &AquaInternalFrameUIJNIClass, methodName: "exportMinimizeIcon", methodSig: "()Ljavax/swing/Icon;", methodCache: &exportMinimizeIcon_MethodID_4, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? javax_swing.IconForward( javaObject: __return ) : nil
    }


    /// public static javax.swing.Icon com.apple.laf.AquaInternalFrameUI.exportZoomIcon()

    private static var exportZoomIcon_MethodID_5: jmethodID?

    open class func exportZoomIcon() -> javax_swing.Icon! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaInternalFrameUI", classCache: &AquaInternalFrameUIJNIClass, methodName: "exportZoomIcon", methodSig: "()Ljavax/swing/Icon;", methodCache: &exportZoomIcon_MethodID_5, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? javax_swing.IconForward( javaObject: __return ) : nil
    }


    /// static void com.apple.laf.AquaInternalFrameUI.updateComponentTreeUIActivation(java.awt.Component,java.lang.Object)

    // Skipping method: true false false false false 

    /// javax.swing.ActionMap com.apple.laf.AquaInternalFrameUI.createActionMap()

    // Skipping method: true false false false false 

    /// protected javax.swing.event.MouseInputAdapter com.apple.laf.AquaInternalFrameUI.createBorderListener(javax.swing.JInternalFrame)

    private static var createBorderListener_MethodID_6: jmethodID?

    open func createBorderListener( arg0: javax_swing.JInternalFrame? ) -> javax_swing.MouseInputAdapter! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "createBorderListener", methodSig: "(Ljavax/swing/JInternalFrame;)Ljavax/swing/event/MouseInputAdapter;", methodCache: &AquaInternalFrameUI.createBorderListener_MethodID_6, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? javax_swing.MouseInputAdapter( javaObject: __return ) : nil
    }

    override open func createBorderListener( _ _arg0: javax_swing.JInternalFrame? ) -> javax_swing.MouseInputAdapter! {
        return createBorderListener( arg0: _arg0 )
    }

    /// protected void com.apple.laf.AquaInternalFrameUI.deinstallMouseHandlers(javax.swing.JComponent)

    private static var deinstallMouseHandlers_MethodID_7: jmethodID?

    open func deinstallMouseHandlers( arg0: javax_swing.JComponent? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "deinstallMouseHandlers", methodSig: "(Ljavax/swing/JComponent;)V", methodCache: &AquaInternalFrameUI.deinstallMouseHandlers_MethodID_7, args: &__args, locals: &__locals )
    }

    override open func deinstallMouseHandlers( _ _arg0: javax_swing.JComponent? ) {
        deinstallMouseHandlers( arg0: _arg0 )
    }

    /// public boolean com.apple.laf.AquaInternalFrameUI.getMouseOverPressedButton()

    private static var getMouseOverPressedButton_MethodID_8: jmethodID?

    open func getMouseOverPressedButton() -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "getMouseOverPressedButton", methodSig: "()Z", methodCache: &AquaInternalFrameUI.getMouseOverPressedButton_MethodID_8, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }


    /// public java.awt.Dimension com.apple.laf.AquaInternalFrameUI.getPreferredSize(javax.swing.JComponent)

    private static var getPreferredSize_MethodID_9: jmethodID?

    open func getPreferredSize( arg0: javax_swing.JComponent? ) -> java_awt.Dimension! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getPreferredSize", methodSig: "(Ljavax/swing/JComponent;)Ljava/awt/Dimension;", methodCache: &AquaInternalFrameUI.getPreferredSize_MethodID_9, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_awt.Dimension( javaObject: __return ) : nil
    }

    override open func getPreferredSize( _ _arg0: javax_swing.JComponent? ) -> java_awt.Dimension! {
        return getPreferredSize( arg0: _arg0 )
    }

    /// public boolean com.apple.laf.AquaInternalFrameUI.getRollover()

    private static var getRollover_MethodID_10: jmethodID?

    open func getRollover() -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "getRollover", methodSig: "()Z", methodCache: &AquaInternalFrameUI.getRollover_MethodID_10, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }


    /// public int com.apple.laf.AquaInternalFrameUI.getWhichButtonPressed()

    private static var getWhichButtonPressed_MethodID_11: jmethodID?

    open func getWhichButtonPressed() -> Int {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallIntMethod( object: javaObject, methodName: "getWhichButtonPressed", methodSig: "()I", methodCache: &AquaInternalFrameUI.getWhichButtonPressed_MethodID_11, args: &__args, locals: &__locals )
        return Int(__return)
    }


    /// protected void com.apple.laf.AquaInternalFrameUI.installComponents()

    private static var installComponents_MethodID_12: jmethodID?

    override open func installComponents() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "installComponents", methodSig: "()V", methodCache: &AquaInternalFrameUI.installComponents_MethodID_12, args: &__args, locals: &__locals )
    }


    /// protected void com.apple.laf.AquaInternalFrameUI.installDefaults()

    private static var installDefaults_MethodID_13: jmethodID?

    override open func installDefaults() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "installDefaults", methodSig: "()V", methodCache: &AquaInternalFrameUI.installDefaults_MethodID_13, args: &__args, locals: &__locals )
    }


    /// protected void com.apple.laf.AquaInternalFrameUI.installKeyboardActions()

    private static var installKeyboardActions_MethodID_14: jmethodID?

    override open func installKeyboardActions() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "installKeyboardActions", methodSig: "()V", methodCache: &AquaInternalFrameUI.installKeyboardActions_MethodID_14, args: &__args, locals: &__locals )
    }


    /// protected void com.apple.laf.AquaInternalFrameUI.installListeners()

    private static var installListeners_MethodID_15: jmethodID?

    override open func installListeners() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "installListeners", methodSig: "()V", methodCache: &AquaInternalFrameUI.installListeners_MethodID_15, args: &__args, locals: &__locals )
    }


    /// protected void com.apple.laf.AquaInternalFrameUI.installMouseHandlers(javax.swing.JComponent)

    private static var installMouseHandlers_MethodID_16: jmethodID?

    open func installMouseHandlers( arg0: javax_swing.JComponent? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "installMouseHandlers", methodSig: "(Ljavax/swing/JComponent;)V", methodCache: &AquaInternalFrameUI.installMouseHandlers_MethodID_16, args: &__args, locals: &__locals )
    }

    override open func installMouseHandlers( _ _arg0: javax_swing.JComponent? ) {
        installMouseHandlers( arg0: _arg0 )
    }

    /// public void com.apple.laf.AquaInternalFrameUI.installUI(javax.swing.JComponent)

    private static var installUI_MethodID_17: jmethodID?

    open func installUI( arg0: javax_swing.JComponent? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "installUI", methodSig: "(Ljavax/swing/JComponent;)V", methodCache: &AquaInternalFrameUI.installUI_MethodID_17, args: &__args, locals: &__locals )
    }

    override open func installUI( _ _arg0: javax_swing.JComponent? ) {
        installUI( arg0: _arg0 )
    }

    /// public boolean com.apple.laf.AquaInternalFrameUI.isDocumentEdited()

    private static var isDocumentEdited_MethodID_18: jmethodID?

    open func isDocumentEdited() -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "isDocumentEdited", methodSig: "()Z", methodCache: &AquaInternalFrameUI.isDocumentEdited_MethodID_18, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }


    /// protected void com.apple.laf.AquaInternalFrameUI.replacePane(javax.swing.JComponent,javax.swing.JComponent)

    private static var replacePane_MethodID_19: jmethodID?

    open func replacePane( arg0: javax_swing.JComponent?, arg1: javax_swing.JComponent? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        __args[1] = JNIType.toJava( value: arg1, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "replacePane", methodSig: "(Ljavax/swing/JComponent;Ljavax/swing/JComponent;)V", methodCache: &AquaInternalFrameUI.replacePane_MethodID_19, args: &__args, locals: &__locals )
    }

    override open func replacePane( _ _arg0: javax_swing.JComponent?, _ _arg1: javax_swing.JComponent? ) {
        replacePane( arg0: _arg0, arg1: _arg1 )
    }

    /// public void com.apple.laf.AquaInternalFrameUI.setDocumentEdited(boolean)

    private static var setDocumentEdited_MethodID_20: jmethodID?

    open func setDocumentEdited( arg0: Bool ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = jvalue( z: jboolean(arg0 ? JNI_TRUE : JNI_FALSE) )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "setDocumentEdited", methodSig: "(Z)V", methodCache: &AquaInternalFrameUI.setDocumentEdited_MethodID_20, args: &__args, locals: &__locals )
    }

    open func setDocumentEdited( _ _arg0: Bool ) {
        setDocumentEdited( arg0: _arg0 )
    }

    /// void com.apple.laf.AquaInternalFrameUI.setFrameType(java.lang.String)

    // Skipping method: true false false false false 

    /// public void com.apple.laf.AquaInternalFrameUI.setNorthPane(javax.swing.JComponent)

    private static var setNorthPane_MethodID_21: jmethodID?

    open func setNorthPane( arg0: javax_swing.JComponent? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "setNorthPane", methodSig: "(Ljavax/swing/JComponent;)V", methodCache: &AquaInternalFrameUI.setNorthPane_MethodID_21, args: &__args, locals: &__locals )
    }

    override open func setNorthPane( _ _arg0: javax_swing.JComponent? ) {
        setNorthPane( arg0: _arg0 )
    }

    /// public void com.apple.laf.AquaInternalFrameUI.setPalette(boolean)

    private static var setPalette_MethodID_22: jmethodID?

    open func setPalette( arg0: Bool ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = jvalue( z: jboolean(arg0 ? JNI_TRUE : JNI_FALSE) )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "setPalette", methodSig: "(Z)V", methodCache: &AquaInternalFrameUI.setPalette_MethodID_22, args: &__args, locals: &__locals )
    }

    open func setPalette( _ _arg0: Bool ) {
        setPalette( arg0: _arg0 )
    }

    /// public void com.apple.laf.AquaInternalFrameUI.setSouthPane(javax.swing.JComponent)

    private static var setSouthPane_MethodID_23: jmethodID?

    open func setSouthPane( arg0: javax_swing.JComponent? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "setSouthPane", methodSig: "(Ljavax/swing/JComponent;)V", methodCache: &AquaInternalFrameUI.setSouthPane_MethodID_23, args: &__args, locals: &__locals )
    }

    override open func setSouthPane( _ _arg0: javax_swing.JComponent? ) {
        setSouthPane( arg0: _arg0 )
    }

    /// protected void com.apple.laf.AquaInternalFrameUI.uninstallKeyboardActions()

    private static var uninstallKeyboardActions_MethodID_24: jmethodID?

    override open func uninstallKeyboardActions() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "uninstallKeyboardActions", methodSig: "()V", methodCache: &AquaInternalFrameUI.uninstallKeyboardActions_MethodID_24, args: &__args, locals: &__locals )
    }


    /// protected void com.apple.laf.AquaInternalFrameUI.uninstallListeners()

    private static var uninstallListeners_MethodID_25: jmethodID?

    override open func uninstallListeners() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "uninstallListeners", methodSig: "()V", methodCache: &AquaInternalFrameUI.uninstallListeners_MethodID_25, args: &__args, locals: &__locals )
    }


}

