
import java_swift
import java_lang
import javax_swing
import java_awt

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home ///
/// Tue Dec 20 11:52:06 GMT 2016 ///

/// class com.apple.laf.AquaImageFactory ///

open class AquaImageFactory: java_lang.JavaObject {

    public convenience init?( casting object: java_lang.JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        if !object.validDownCast( toJavaClass: "com.apple.laf.AquaImageFactory", file, line ) {
            return nil
        }
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var AquaImageFactoryJNIClass: jclass?

    /// private static final int com.apple.laf.AquaImageFactory.kAlertIconSize

    /// protected static final com.apple.laf.AquaImageFactory$NamedImageSingleton com.apple.laf.AquaImageFactory.northArrow

    /// protected static final com.apple.laf.AquaImageFactory$IconUIResourceSingleton com.apple.laf.AquaImageFactory.northArrowIcon

    /// protected static final com.apple.laf.AquaImageFactory$NamedImageSingleton com.apple.laf.AquaImageFactory.southArrow

    /// protected static final com.apple.laf.AquaImageFactory$IconUIResourceSingleton com.apple.laf.AquaImageFactory.southArrowIcon

    /// protected static final com.apple.laf.AquaImageFactory$NamedImageSingleton com.apple.laf.AquaImageFactory.westArrow

    /// protected static final com.apple.laf.AquaImageFactory$IconUIResourceSingleton com.apple.laf.AquaImageFactory.westArrowIcon

    /// protected static final com.apple.laf.AquaImageFactory$NamedImageSingleton com.apple.laf.AquaImageFactory.eastArrow

    /// protected static final com.apple.laf.AquaImageFactory$IconUIResourceSingleton com.apple.laf.AquaImageFactory.eastArrowIcon

    /// public com.apple.laf.AquaImageFactory()

    private static var new_MethodID_1: jmethodID?

    public convenience init() {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __object = JNIMethod.NewObject( className: "com/apple/laf/AquaImageFactory", classCache: &AquaImageFactory.AquaImageFactoryJNIClass, methodSig: "()V", methodCache: &AquaImageFactory.new_MethodID_1, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    /// public static javax.swing.plaf.IconUIResource com.apple.laf.AquaImageFactory.getConfirmImageIcon()

    private static var getConfirmImageIcon_MethodID_2: jmethodID?

    open class func getConfirmImageIcon() -> javax_swing.IconUIResource! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaImageFactory", classCache: &AquaImageFactoryJNIClass, methodName: "getConfirmImageIcon", methodSig: "()Ljavax/swing/plaf/IconUIResource;", methodCache: &getConfirmImageIcon_MethodID_2, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? javax_swing.IconUIResource( javaObject: __return ) : nil
    }


    /// public static javax.swing.plaf.IconUIResource com.apple.laf.AquaImageFactory.getCautionImageIcon()

    private static var getCautionImageIcon_MethodID_3: jmethodID?

    open class func getCautionImageIcon() -> javax_swing.IconUIResource! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaImageFactory", classCache: &AquaImageFactoryJNIClass, methodName: "getCautionImageIcon", methodSig: "()Ljavax/swing/plaf/IconUIResource;", methodCache: &getCautionImageIcon_MethodID_3, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? javax_swing.IconUIResource( javaObject: __return ) : nil
    }


    /// public static javax.swing.plaf.IconUIResource com.apple.laf.AquaImageFactory.getStopImageIcon()

    private static var getStopImageIcon_MethodID_4: jmethodID?

    open class func getStopImageIcon() -> javax_swing.IconUIResource! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaImageFactory", classCache: &AquaImageFactoryJNIClass, methodName: "getStopImageIcon", methodSig: "()Ljavax/swing/plaf/IconUIResource;", methodCache: &getStopImageIcon_MethodID_4, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? javax_swing.IconUIResource( javaObject: __return ) : nil
    }


    /// public static javax.swing.plaf.IconUIResource com.apple.laf.AquaImageFactory.getLockImageIcon()

    private static var getLockImageIcon_MethodID_5: jmethodID?

    open class func getLockImageIcon() -> javax_swing.IconUIResource! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaImageFactory", classCache: &AquaImageFactoryJNIClass, methodName: "getLockImageIcon", methodSig: "()Ljavax/swing/plaf/IconUIResource;", methodCache: &getLockImageIcon_MethodID_5, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? javax_swing.IconUIResource( javaObject: __return ) : nil
    }


    /// public static javax.swing.Icon com.apple.laf.AquaImageFactory.getMenuItemCheckIcon()

    private static var getMenuItemCheckIcon_MethodID_6: jmethodID?

    open class func getMenuItemCheckIcon() -> javax_swing.Icon! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaImageFactory", classCache: &AquaImageFactoryJNIClass, methodName: "getMenuItemCheckIcon", methodSig: "()Ljavax/swing/Icon;", methodCache: &getMenuItemCheckIcon_MethodID_6, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? javax_swing.IconForward( javaObject: __return ) : nil
    }


    /// public static javax.swing.Icon com.apple.laf.AquaImageFactory.getMenuItemDashIcon()

    private static var getMenuItemDashIcon_MethodID_7: jmethodID?

    open class func getMenuItemDashIcon() -> javax_swing.Icon! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaImageFactory", classCache: &AquaImageFactoryJNIClass, methodName: "getMenuItemDashIcon", methodSig: "()Ljavax/swing/Icon;", methodCache: &getMenuItemDashIcon_MethodID_7, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? javax_swing.IconForward( javaObject: __return ) : nil
    }


    /// public static javax.swing.Icon com.apple.laf.AquaImageFactory.getMenuArrowIcon()

    private static var getMenuArrowIcon_MethodID_8: jmethodID?

    open class func getMenuArrowIcon() -> javax_swing.Icon! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaImageFactory", classCache: &AquaImageFactoryJNIClass, methodName: "getMenuArrowIcon", methodSig: "()Ljavax/swing/Icon;", methodCache: &getMenuArrowIcon_MethodID_8, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? javax_swing.IconForward( javaObject: __return ) : nil
    }


    /// public static javax.swing.plaf.IconUIResource com.apple.laf.AquaImageFactory.getTreeOpenFolderIcon()

    private static var getTreeOpenFolderIcon_MethodID_9: jmethodID?

    open class func getTreeOpenFolderIcon() -> javax_swing.IconUIResource! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaImageFactory", classCache: &AquaImageFactoryJNIClass, methodName: "getTreeOpenFolderIcon", methodSig: "()Ljavax/swing/plaf/IconUIResource;", methodCache: &getTreeOpenFolderIcon_MethodID_9, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? javax_swing.IconUIResource( javaObject: __return ) : nil
    }


    /// public static javax.swing.plaf.IconUIResource com.apple.laf.AquaImageFactory.getTreeFolderIcon()

    private static var getTreeFolderIcon_MethodID_10: jmethodID?

    open class func getTreeFolderIcon() -> javax_swing.IconUIResource! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaImageFactory", classCache: &AquaImageFactoryJNIClass, methodName: "getTreeFolderIcon", methodSig: "()Ljavax/swing/plaf/IconUIResource;", methodCache: &getTreeFolderIcon_MethodID_10, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? javax_swing.IconUIResource( javaObject: __return ) : nil
    }


    /// public static javax.swing.plaf.IconUIResource com.apple.laf.AquaImageFactory.getTreeDocumentIcon()

    private static var getTreeDocumentIcon_MethodID_11: jmethodID?

    open class func getTreeDocumentIcon() -> javax_swing.IconUIResource! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaImageFactory", classCache: &AquaImageFactoryJNIClass, methodName: "getTreeDocumentIcon", methodSig: "()Ljavax/swing/plaf/IconUIResource;", methodCache: &getTreeDocumentIcon_MethodID_11, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? javax_swing.IconUIResource( javaObject: __return ) : nil
    }


    /// public static javax.swing.plaf.UIResource com.apple.laf.AquaImageFactory.getTreeExpandedIcon()

    private static var getTreeExpandedIcon_MethodID_12: jmethodID?

    open class func getTreeExpandedIcon() -> javax_swing.UIResource! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaImageFactory", classCache: &AquaImageFactoryJNIClass, methodName: "getTreeExpandedIcon", methodSig: "()Ljavax/swing/plaf/UIResource;", methodCache: &getTreeExpandedIcon_MethodID_12, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? javax_swing.UIResourceForward( javaObject: __return ) : nil
    }


    /// public static javax.swing.plaf.UIResource com.apple.laf.AquaImageFactory.getTreeCollapsedIcon()

    private static var getTreeCollapsedIcon_MethodID_13: jmethodID?

    open class func getTreeCollapsedIcon() -> javax_swing.UIResource! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaImageFactory", classCache: &AquaImageFactoryJNIClass, methodName: "getTreeCollapsedIcon", methodSig: "()Ljavax/swing/plaf/UIResource;", methodCache: &getTreeCollapsedIcon_MethodID_13, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? javax_swing.UIResourceForward( javaObject: __return ) : nil
    }


    /// public static javax.swing.plaf.UIResource com.apple.laf.AquaImageFactory.getTreeRightToLeftCollapsedIcon()

    private static var getTreeRightToLeftCollapsedIcon_MethodID_14: jmethodID?

    open class func getTreeRightToLeftCollapsedIcon() -> javax_swing.UIResource! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaImageFactory", classCache: &AquaImageFactoryJNIClass, methodName: "getTreeRightToLeftCollapsedIcon", methodSig: "()Ljavax/swing/plaf/UIResource;", methodCache: &getTreeRightToLeftCollapsedIcon_MethodID_14, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? javax_swing.UIResourceForward( javaObject: __return ) : nil
    }


    /// public static java.awt.Color com.apple.laf.AquaImageFactory.getSelectionBackgroundColorUIResource()

    private static var getSelectionBackgroundColorUIResource_MethodID_15: jmethodID?

    open class func getSelectionBackgroundColorUIResource() -> java_awt.Color! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaImageFactory", classCache: &AquaImageFactoryJNIClass, methodName: "getSelectionBackgroundColorUIResource", methodSig: "()Ljava/awt/Color;", methodCache: &getSelectionBackgroundColorUIResource_MethodID_15, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_awt.Color( javaObject: __return ) : nil
    }


    /// public static java.awt.Color com.apple.laf.AquaImageFactory.getSelectionForegroundColorUIResource()

    private static var getSelectionForegroundColorUIResource_MethodID_16: jmethodID?

    open class func getSelectionForegroundColorUIResource() -> java_awt.Color! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaImageFactory", classCache: &AquaImageFactoryJNIClass, methodName: "getSelectionForegroundColorUIResource", methodSig: "()Ljava/awt/Color;", methodCache: &getSelectionForegroundColorUIResource_MethodID_16, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_awt.Color( javaObject: __return ) : nil
    }


    /// public static java.awt.Color com.apple.laf.AquaImageFactory.getSelectionInactiveBackgroundColorUIResource()

    private static var getSelectionInactiveBackgroundColorUIResource_MethodID_17: jmethodID?

    open class func getSelectionInactiveBackgroundColorUIResource() -> java_awt.Color! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaImageFactory", classCache: &AquaImageFactoryJNIClass, methodName: "getSelectionInactiveBackgroundColorUIResource", methodSig: "()Ljava/awt/Color;", methodCache: &getSelectionInactiveBackgroundColorUIResource_MethodID_17, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_awt.Color( javaObject: __return ) : nil
    }


    /// public static java.awt.Color com.apple.laf.AquaImageFactory.getSelectionInactiveForegroundColorUIResource()

    private static var getSelectionInactiveForegroundColorUIResource_MethodID_18: jmethodID?

    open class func getSelectionInactiveForegroundColorUIResource() -> java_awt.Color! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaImageFactory", classCache: &AquaImageFactoryJNIClass, methodName: "getSelectionInactiveForegroundColorUIResource", methodSig: "()Ljava/awt/Color;", methodCache: &getSelectionInactiveForegroundColorUIResource_MethodID_18, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_awt.Color( javaObject: __return ) : nil
    }


    /// public static java.awt.Color com.apple.laf.AquaImageFactory.getTextSelectionForegroundColorUIResource()

    private static var getTextSelectionForegroundColorUIResource_MethodID_19: jmethodID?

    open class func getTextSelectionForegroundColorUIResource() -> java_awt.Color! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaImageFactory", classCache: &AquaImageFactoryJNIClass, methodName: "getTextSelectionForegroundColorUIResource", methodSig: "()Ljava/awt/Color;", methodCache: &getTextSelectionForegroundColorUIResource_MethodID_19, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_awt.Color( javaObject: __return ) : nil
    }


    /// public static java.awt.Color com.apple.laf.AquaImageFactory.getTextSelectionBackgroundColorUIResource()

    private static var getTextSelectionBackgroundColorUIResource_MethodID_20: jmethodID?

    open class func getTextSelectionBackgroundColorUIResource() -> java_awt.Color! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaImageFactory", classCache: &AquaImageFactoryJNIClass, methodName: "getTextSelectionBackgroundColorUIResource", methodSig: "()Ljava/awt/Color;", methodCache: &getTextSelectionBackgroundColorUIResource_MethodID_20, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_awt.Color( javaObject: __return ) : nil
    }


    /// public static java.awt.Color com.apple.laf.AquaImageFactory.getFocusRingColorUIResource()

    private static var getFocusRingColorUIResource_MethodID_21: jmethodID?

    open class func getFocusRingColorUIResource() -> java_awt.Color! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaImageFactory", classCache: &AquaImageFactoryJNIClass, methodName: "getFocusRingColorUIResource", methodSig: "()Ljava/awt/Color;", methodCache: &getFocusRingColorUIResource_MethodID_21, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_awt.Color( javaObject: __return ) : nil
    }


    /// public static java.awt.Color com.apple.laf.AquaImageFactory.getWindowBackgroundColorUIResource()

    private static var getWindowBackgroundColorUIResource_MethodID_22: jmethodID?

    open class func getWindowBackgroundColorUIResource() -> java_awt.Color! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "com/apple/laf/AquaImageFactory", classCache: &AquaImageFactoryJNIClass, methodName: "getWindowBackgroundColorUIResource", methodSig: "()Ljava/awt/Color;", methodCache: &getWindowBackgroundColorUIResource_MethodID_22, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_awt.Color( javaObject: __return ) : nil
    }


    /// static java.awt.Image com.apple.laf.AquaImageFactory.getThisApplicationsIcon(int,int)

    /// static java.awt.Image com.apple.laf.AquaImageFactory.getGenericJavaIcon()

    /// static java.lang.String com.apple.laf.AquaImageFactory.getPathToThisApplication()

    /// static javax.swing.plaf.IconUIResource com.apple.laf.AquaImageFactory.getAppIconCompositedOn(java.awt.Image)

    /// static javax.swing.plaf.IconUIResource com.apple.laf.AquaImageFactory.getAppIconCompositedOn(com.apple.laf.AquaIcon$SystemIcon)

    /// static java.awt.Image com.apple.laf.AquaImageFactory.getArrowImageForDirection(int)

    /// static javax.swing.Icon com.apple.laf.AquaImageFactory.getArrowIconForDirection(int)

}
