
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home ///
/// Tue Aug 08 14:27:28 BST 2017 ///

/// class com.apple.laf.AquaImageFactory$NineSliceMetrics ///

open class AquaImageFactory_NineSliceMetrics: java_swift.JavaObject {

    public convenience init?( casting object: java_swift.JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var AquaImageFactory_NineSliceMetricsJNIClass: jclass?

    /// public final int com.apple.laf.AquaImageFactory$NineSliceMetrics.wCut

    private static var wCut_FieldID: jfieldID?

    open var wCut: Int {
        get {
            var __locals = [jobject]()
            let __value = JNIField.GetIntField( fieldName: "wCut", fieldType: "I", fieldCache: &AquaImageFactory_NineSliceMetrics.wCut_FieldID, object: javaObject, locals: &__locals )
            return JNIType.toSwift( type: Int(), from: __value )
        }
    }

    /// public final int com.apple.laf.AquaImageFactory$NineSliceMetrics.eCut

    private static var eCut_FieldID: jfieldID?

    open var eCut: Int {
        get {
            var __locals = [jobject]()
            let __value = JNIField.GetIntField( fieldName: "eCut", fieldType: "I", fieldCache: &AquaImageFactory_NineSliceMetrics.eCut_FieldID, object: javaObject, locals: &__locals )
            return JNIType.toSwift( type: Int(), from: __value )
        }
    }

    /// public final int com.apple.laf.AquaImageFactory$NineSliceMetrics.nCut

    private static var nCut_FieldID: jfieldID?

    open var nCut: Int {
        get {
            var __locals = [jobject]()
            let __value = JNIField.GetIntField( fieldName: "nCut", fieldType: "I", fieldCache: &AquaImageFactory_NineSliceMetrics.nCut_FieldID, object: javaObject, locals: &__locals )
            return JNIType.toSwift( type: Int(), from: __value )
        }
    }

    /// public final int com.apple.laf.AquaImageFactory$NineSliceMetrics.sCut

    private static var sCut_FieldID: jfieldID?

    open var sCut: Int {
        get {
            var __locals = [jobject]()
            let __value = JNIField.GetIntField( fieldName: "sCut", fieldType: "I", fieldCache: &AquaImageFactory_NineSliceMetrics.sCut_FieldID, object: javaObject, locals: &__locals )
            return JNIType.toSwift( type: Int(), from: __value )
        }
    }

    /// public final int com.apple.laf.AquaImageFactory$NineSliceMetrics.minW

    private static var minW_FieldID: jfieldID?

    open var minW: Int {
        get {
            var __locals = [jobject]()
            let __value = JNIField.GetIntField( fieldName: "minW", fieldType: "I", fieldCache: &AquaImageFactory_NineSliceMetrics.minW_FieldID, object: javaObject, locals: &__locals )
            return JNIType.toSwift( type: Int(), from: __value )
        }
    }

    /// public final int com.apple.laf.AquaImageFactory$NineSliceMetrics.minH

    private static var minH_FieldID: jfieldID?

    open var minH: Int {
        get {
            var __locals = [jobject]()
            let __value = JNIField.GetIntField( fieldName: "minH", fieldType: "I", fieldCache: &AquaImageFactory_NineSliceMetrics.minH_FieldID, object: javaObject, locals: &__locals )
            return JNIType.toSwift( type: Int(), from: __value )
        }
    }

    /// public final boolean com.apple.laf.AquaImageFactory$NineSliceMetrics.showMiddle

    private static var showMiddle_FieldID: jfieldID?

    open var showMiddle: Bool {
        get {
            var __locals = [jobject]()
            let __value = JNIField.GetBooleanField( fieldName: "showMiddle", fieldType: "Z", fieldCache: &AquaImageFactory_NineSliceMetrics.showMiddle_FieldID, object: javaObject, locals: &__locals )
            return JNIType.toSwift( type: Bool(), from: __value )
        }
    }

    /// public final boolean com.apple.laf.AquaImageFactory$NineSliceMetrics.stretchH

    private static var stretchH_FieldID: jfieldID?

    open var stretchH: Bool {
        get {
            var __locals = [jobject]()
            let __value = JNIField.GetBooleanField( fieldName: "stretchH", fieldType: "Z", fieldCache: &AquaImageFactory_NineSliceMetrics.stretchH_FieldID, object: javaObject, locals: &__locals )
            return JNIType.toSwift( type: Bool(), from: __value )
        }
    }

    /// public final boolean com.apple.laf.AquaImageFactory$NineSliceMetrics.stretchV

    private static var stretchV_FieldID: jfieldID?

    open var stretchV: Bool {
        get {
            var __locals = [jobject]()
            let __value = JNIField.GetBooleanField( fieldName: "stretchV", fieldType: "Z", fieldCache: &AquaImageFactory_NineSliceMetrics.stretchV_FieldID, object: javaObject, locals: &__locals )
            return JNIType.toSwift( type: Bool(), from: __value )
        }
    }

    /// public com.apple.laf.AquaImageFactory$NineSliceMetrics(int,int,int,int,int,int)

    private static var new_MethodID_1: jmethodID?

    public convenience init( arg0: Int, arg1: Int, arg2: Int, arg3: Int, arg4: Int, arg5: Int ) {
        var __args = [jvalue]( repeating: jvalue(), count: 6 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        __args[1] = JNIType.toJava( value: arg1, locals: &__locals )
        __args[2] = JNIType.toJava( value: arg2, locals: &__locals )
        __args[3] = JNIType.toJava( value: arg3, locals: &__locals )
        __args[4] = JNIType.toJava( value: arg4, locals: &__locals )
        __args[5] = JNIType.toJava( value: arg5, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "com/apple/laf/AquaImageFactory$NineSliceMetrics", classCache: &AquaImageFactory_NineSliceMetrics.AquaImageFactory_NineSliceMetricsJNIClass, methodSig: "(IIIIII)V", methodCache: &AquaImageFactory_NineSliceMetrics.new_MethodID_1, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _arg0: Int, _ _arg1: Int, _ _arg2: Int, _ _arg3: Int, _ _arg4: Int, _ _arg5: Int ) {
        self.init( arg0: _arg0, arg1: _arg1, arg2: _arg2, arg3: _arg3, arg4: _arg4, arg5: _arg5 )
    }

    /// public com.apple.laf.AquaImageFactory$NineSliceMetrics(int,int,int,int,int,int,boolean)

    private static var new_MethodID_2: jmethodID?

    public convenience init( arg0: Int, arg1: Int, arg2: Int, arg3: Int, arg4: Int, arg5: Int, arg6: Bool ) {
        var __args = [jvalue]( repeating: jvalue(), count: 7 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        __args[1] = JNIType.toJava( value: arg1, locals: &__locals )
        __args[2] = JNIType.toJava( value: arg2, locals: &__locals )
        __args[3] = JNIType.toJava( value: arg3, locals: &__locals )
        __args[4] = JNIType.toJava( value: arg4, locals: &__locals )
        __args[5] = JNIType.toJava( value: arg5, locals: &__locals )
        __args[6] = JNIType.toJava( value: arg6, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "com/apple/laf/AquaImageFactory$NineSliceMetrics", classCache: &AquaImageFactory_NineSliceMetrics.AquaImageFactory_NineSliceMetricsJNIClass, methodSig: "(IIIIIIZ)V", methodCache: &AquaImageFactory_NineSliceMetrics.new_MethodID_2, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _arg0: Int, _ _arg1: Int, _ _arg2: Int, _ _arg3: Int, _ _arg4: Int, _ _arg5: Int, _ _arg6: Bool ) {
        self.init( arg0: _arg0, arg1: _arg1, arg2: _arg2, arg3: _arg3, arg4: _arg4, arg5: _arg5, arg6: _arg6 )
    }

    /// public com.apple.laf.AquaImageFactory$NineSliceMetrics(int,int,int,int,int,int,boolean,boolean,boolean)

    private static var new_MethodID_3: jmethodID?

    public convenience init( arg0: Int, arg1: Int, arg2: Int, arg3: Int, arg4: Int, arg5: Int, arg6: Bool, arg7: Bool, arg8: Bool ) {
        var __args = [jvalue]( repeating: jvalue(), count: 9 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        __args[1] = JNIType.toJava( value: arg1, locals: &__locals )
        __args[2] = JNIType.toJava( value: arg2, locals: &__locals )
        __args[3] = JNIType.toJava( value: arg3, locals: &__locals )
        __args[4] = JNIType.toJava( value: arg4, locals: &__locals )
        __args[5] = JNIType.toJava( value: arg5, locals: &__locals )
        __args[6] = JNIType.toJava( value: arg6, locals: &__locals )
        __args[7] = JNIType.toJava( value: arg7, locals: &__locals )
        __args[8] = JNIType.toJava( value: arg8, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "com/apple/laf/AquaImageFactory$NineSliceMetrics", classCache: &AquaImageFactory_NineSliceMetrics.AquaImageFactory_NineSliceMetricsJNIClass, methodSig: "(IIIIIIZZZ)V", methodCache: &AquaImageFactory_NineSliceMetrics.new_MethodID_3, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _arg0: Int, _ _arg1: Int, _ _arg2: Int, _ _arg3: Int, _ _arg4: Int, _ _arg5: Int, _ _arg6: Bool, _ _arg7: Bool, _ _arg8: Bool ) {
        self.init( arg0: _arg0, arg1: _arg1, arg2: _arg2, arg3: _arg3, arg4: _arg4, arg5: _arg5, arg6: _arg6, arg7: _arg7, arg8: _arg8 )
    }

}

