
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// interface com.apple.eawt.event.GesturePhaseListener ///

public protocol GesturePhaseListener: GestureListener {

    /// public abstract void com.apple.eawt.event.GesturePhaseListener.gestureBegan(com.apple.eawt.event.GesturePhaseEvent)

    func gestureBegan( arg0: GesturePhaseEvent? )

    /// public abstract void com.apple.eawt.event.GesturePhaseListener.gestureEnded(com.apple.eawt.event.GesturePhaseEvent)

    func gestureEnded( arg0: GesturePhaseEvent? )

}


open class GesturePhaseListenerForward: GestureListenerForward, GesturePhaseListener {

    private static var GesturePhaseListenerJNIClass: jclass?

    /// public abstract void com.apple.eawt.event.GesturePhaseListener.gestureBegan(com.apple.eawt.event.GesturePhaseEvent)

    private static var gestureBegan_MethodID_3: jmethodID?

    open func gestureBegan( arg0: GesturePhaseEvent? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "gestureBegan", methodSig: "(Lcom/apple/eawt/event/GesturePhaseEvent;)V", methodCache: &GesturePhaseListenerForward.gestureBegan_MethodID_3, args: &__args, locals: &__locals )
    }

    open func gestureBegan( _ _arg0: GesturePhaseEvent? ) {
        gestureBegan( arg0: _arg0 )
    }

    /// public abstract void com.apple.eawt.event.GesturePhaseListener.gestureEnded(com.apple.eawt.event.GesturePhaseEvent)

    private static var gestureEnded_MethodID_4: jmethodID?

    open func gestureEnded( arg0: GesturePhaseEvent? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "gestureEnded", methodSig: "(Lcom/apple/eawt/event/GesturePhaseEvent;)V", methodCache: &GesturePhaseListenerForward.gestureEnded_MethodID_4, args: &__args, locals: &__locals )
    }

    open func gestureEnded( _ _arg0: GesturePhaseEvent? ) {
        gestureEnded( arg0: _arg0 )
    }

}

private typealias GesturePhaseListener_gestureBegan_0_type = @convention(c) ( _: UnsafeMutablePointer<JNIEnv?>, _: jobject?, _: jlong, _: jobject? ) -> ()

private func GesturePhaseListener_gestureBegan_0( _ __env: UnsafeMutablePointer<JNIEnv?>, _ __this: jobject?, _ __swiftObject: jlong, _ arg0: jobject? ) -> () {
    GesturePhaseListenerLocal_.swiftObject( jniEnv: __env, javaObject: __this, swiftObject: __swiftObject ).gestureBegan( arg0: arg0 != nil ? GesturePhaseEvent( javaObject: arg0 ) : nil )
}

private typealias GesturePhaseListener_gestureEnded_1_type = @convention(c) ( _: UnsafeMutablePointer<JNIEnv?>, _: jobject?, _: jlong, _: jobject? ) -> ()

private func GesturePhaseListener_gestureEnded_1( _ __env: UnsafeMutablePointer<JNIEnv?>, _ __this: jobject?, _ __swiftObject: jlong, _ arg0: jobject? ) -> () {
    GesturePhaseListenerLocal_.swiftObject( jniEnv: __env, javaObject: __this, swiftObject: __swiftObject ).gestureEnded( arg0: arg0 != nil ? GesturePhaseEvent( javaObject: arg0 ) : nil )
}

fileprivate class GesturePhaseListenerLocal_: JNILocalProxy<GesturePhaseListener, Any> {

    fileprivate static let _proxyClass: jclass = {
        var natives = [JNINativeMethod]()

        let GesturePhaseListener_gestureBegan_0_thunk: GesturePhaseListener_gestureBegan_0_type = GesturePhaseListener_gestureBegan_0
        natives.append( JNINativeMethod( name: strdup("__gestureBegan"), signature: strdup("(JLcom/apple/eawt/event/GesturePhaseEvent;)V"), fnPtr: unsafeBitCast( GesturePhaseListener_gestureBegan_0_thunk, to: UnsafeMutableRawPointer.self ) ) )

        let GesturePhaseListener_gestureEnded_1_thunk: GesturePhaseListener_gestureEnded_1_type = GesturePhaseListener_gestureEnded_1
        natives.append( JNINativeMethod( name: strdup("__gestureEnded"), signature: strdup("(JLcom/apple/eawt/event/GesturePhaseEvent;)V"), fnPtr: unsafeBitCast( GesturePhaseListener_gestureEnded_1_thunk, to: UnsafeMutableRawPointer.self ) ) )

        natives.append( JNINativeMethod( name: strdup("__finalize"), signature: strdup("(J)V"), fnPtr: unsafeBitCast( JNIReleasableProxy__finalize_thunk, to: UnsafeMutableRawPointer.self ) ) )

        let clazz = JNI.FindClass( proxyClassName() )
        natives.withUnsafeBufferPointer {
            nativesPtr in
            if JNI.api.RegisterNatives( JNI.env, clazz, nativesPtr.baseAddress, jint(nativesPtr.count) ) != jint(JNI_OK) {
                JNI.report( "Unable to register java natives" )
            }
        }

        defer { JNI.DeleteLocalRef( clazz ) }
        return JNI.api.NewGlobalRef( JNI.env, clazz )!
    }()

    override open class func proxyClassName() -> String { return "org/swiftjava/com_apple/GesturePhaseListenerProxy" }
    override open class func proxyClass() -> jclass? { return _proxyClass }

}

extension GesturePhaseListener {

    public func localJavaObject( _ locals: UnsafeMutablePointer<[jobject]> ) -> jobject? {
        return GesturePhaseListenerLocal_( owned: self, proto: self ).localJavaObject( locals )
    }

}

open class GesturePhaseListenerBase: GesturePhaseListener {

    public init() {}

    /// public abstract void com.apple.eawt.event.GesturePhaseListener.gestureBegan(com.apple.eawt.event.GesturePhaseEvent)

    open func gestureBegan( arg0: GesturePhaseEvent? ) /**/ {
    }


    /// public abstract void com.apple.eawt.event.GesturePhaseListener.gestureEnded(com.apple.eawt.event.GesturePhaseEvent)

    open func gestureEnded( arg0: GesturePhaseEvent? ) /**/ {
    }


}
