
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home ///
/// Tue Aug 08 14:27:27 BST 2017 ///

/// class com.apple.eawt.event.GestureEvent ///

open class GestureEvent: java_swift.JavaObject {

    public convenience init?( casting object: java_swift.JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var GestureEventJNIClass: jclass?

    /// boolean com.apple.eawt.event.GestureEvent.consumed

    /// com.apple.eawt.event.GestureEvent()

    /// protected boolean com.apple.eawt.event.GestureEvent.isConsumed()

    private static var isConsumed_MethodID_1: jmethodID?

    open func isConsumed() -> Bool {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "isConsumed", methodSig: "()Z", methodCache: &GestureEvent.isConsumed_MethodID_1, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: Bool(), from: __return )
    }


    /// public void com.apple.eawt.event.GestureEvent.consume()

    private static var consume_MethodID_2: jmethodID?

    open func consume() {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "consume", methodSig: "()V", methodCache: &GestureEvent.consume_MethodID_2, args: &__args, locals: &__locals )
    }


}

