
import java_swift
import java_util

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// interface com.apple.eawt.event.GestureListener ///

public protocol GestureListener: java_util.EventListener {

}


open class GestureListenerForward: java_util.EventListenerForward, GestureListener {

    private static var GestureListenerJNIClass: jclass?

}

fileprivate class GestureListenerLocal_: JNILocalProxy<GestureListener, Any> {

    fileprivate static let _proxyClass: jclass = {
        var natives = [JNINativeMethod]()

        natives.append( JNINativeMethod( name: strdup("__finalize"), signature: strdup("(J)V"), fnPtr: unsafeBitCast( JNIReleasableProxy__finalize_thunk, to: UnsafeMutableRawPointer.self ) ) )

        let clazz = JNI.FindClass( proxyClassName() )
        withUnsafePointer(to: &natives[0]) {
            nativesPtr in
            if JNI.api.RegisterNatives( JNI.env, clazz, nativesPtr, jint(natives.count) ) != jint(JNI_OK) {
                JNI.report( "Unable to register java natives" )
            }
        }

        defer { JNI.DeleteLocalRef( clazz ) }
        return JNI.api.NewGlobalRef( JNI.env, clazz )!
    }()

    override open class func proxyClassName() -> String { return "org/swiftjava/com_apple/GestureListenerProxy" }
    override open class func proxyClass() -> jclass? { return _proxyClass }

}

extension GestureListener {

    public func localJavaObject( _ locals: UnsafeMutablePointer<[jobject]> ) -> jobject? {
        return GestureListenerLocal_( owned: self, proto: self ).localJavaObject( locals )
    }

}

open class GestureListenerBase: GestureListener {

    public init() {}

}
