
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home ///
/// Tue Aug 08 14:27:27 BST 2017 ///

/// interface com.apple.eawt.event.RotationListener ///

public protocol RotationListener: GestureListener {

    /// public abstract void com.apple.eawt.event.RotationListener.rotate(com.apple.eawt.event.RotationEvent)

    func rotate( arg0: RotationEvent? )

}


open class RotationListenerForward: GestureListenerForward, RotationListener {

    private static var RotationListenerJNIClass: jclass?

    /// public abstract void com.apple.eawt.event.RotationListener.rotate(com.apple.eawt.event.RotationEvent)

    private static var rotate_MethodID_2: jmethodID?

    open func rotate( arg0: RotationEvent? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "rotate", methodSig: "(Lcom/apple/eawt/event/RotationEvent;)V", methodCache: &RotationListenerForward.rotate_MethodID_2, args: &__args, locals: &__locals )
    }

    open func rotate( _ _arg0: RotationEvent? ) {
        rotate( arg0: _arg0 )
    }

}


private typealias RotationListener_rotate_0_type = @convention(c) ( _: UnsafeMutablePointer<JNIEnv?>, _: jobject?, _: jlong, _: jobject? ) -> ()

private func RotationListener_rotate_0( _ __env: UnsafeMutablePointer<JNIEnv?>, _ __this: jobject?, _ __swiftObject: jlong, _ arg0: jobject? ) -> () {
    JNI.inNative = true;
    RotationListenerLocal_.swiftObject( jniEnv: __env, javaObject: __this, swiftObject: __swiftObject ).rotate( arg0: arg0 != nil ? RotationEvent( javaObject: arg0 ) : nil )
    JNI.inNative = false;
}

fileprivate class RotationListenerLocal_: JNILocalProxy<RotationListener, Any> {

    fileprivate static let _proxyClass: jclass = {
        var natives = [JNINativeMethod]()

        let RotationListener_rotate_0_thunk: RotationListener_rotate_0_type = RotationListener_rotate_0
        natives.append( JNINativeMethod( name: strdup("__rotate"), signature: strdup("(JLcom/apple/eawt/event/RotationEvent;)V"), fnPtr: unsafeBitCast( RotationListener_rotate_0_thunk, to: UnsafeMutableRawPointer.self ) ) )

        natives.append( JNINativeMethod( name: strdup("__finalize"), signature: strdup("(J)V"), fnPtr: unsafeBitCast( JNIReleasableProxy__finalize_thunk, to: UnsafeMutableRawPointer.self ) ) )

        let clazz = JNI.FindClass( proxyClassName() )
        withUnsafePointer(to: &natives[0]) {
            nativesPtr in
            if JNI.api.RegisterNatives( JNI.env, clazz, nativesPtr, jint(natives.count) ) != jint(JNI_OK) {
                JNI.report( "Unable to register java natives" )
            }
        }

        defer { JNI.DeleteLocalRef( clazz ) }
        return JNI.api.NewGlobalRef( JNI.env, clazz )!
    }()

    override open class func proxyClassName() -> String { return "org/swiftjava/com_apple/RotationListenerProxy" }
    override open class func proxyClass() -> jclass? { return _proxyClass }

}

extension RotationListener {

    public func localJavaObject( _ locals: UnsafeMutablePointer<[jobject]> ) -> jobject? {
        return RotationListenerLocal_( owned: self, proto: self ).localJavaObject( locals )
    }

}

open class RotationListenerBase: RotationListener {

    public init() {}

    /// public abstract void com.apple.eawt.event.RotationListener.rotate(com.apple.eawt.event.RotationEvent)

    open func rotate( arg0: RotationEvent? ) /**/ {
    }

    open func rotate( _ _arg0: RotationEvent? ) /**/ {
        rotate( arg0: _arg0 )
    }

}
