
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home ///
/// Tue Dec 20 11:52:04 GMT 2016 ///

/// interface com.apple.eawt.SystemSleepListener ///

public protocol SystemSleepListener: AppEventListener {

    /// public abstract void com.apple.eawt.SystemSleepListener.systemAwoke(com.apple.eawt.AppEvent$SystemSleepEvent)

    func systemAwoke( arg0: AppEvent_SystemSleepEvent? )
    func systemAwoke( _ _arg0: AppEvent_SystemSleepEvent? )

    /// public abstract void com.apple.eawt.SystemSleepListener.systemAboutToSleep(com.apple.eawt.AppEvent$SystemSleepEvent)

    func systemAboutToSleep( arg0: AppEvent_SystemSleepEvent? )
    func systemAboutToSleep( _ _arg0: AppEvent_SystemSleepEvent? )

}

open class SystemSleepListenerForward: AppEventListenerForward, SystemSleepListener {

    private static var SystemSleepListenerJNIClass: jclass?

    /// public abstract void com.apple.eawt.SystemSleepListener.systemAwoke(com.apple.eawt.AppEvent$SystemSleepEvent)

    private static var systemAwoke_MethodID_3: jmethodID?

    open func systemAwoke( arg0: AppEvent_SystemSleepEvent? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "systemAwoke", methodSig: "(Lcom/apple/eawt/AppEvent$SystemSleepEvent;)V", methodCache: &SystemSleepListenerForward.systemAwoke_MethodID_3, args: &__args, locals: &__locals )
    }

    open func systemAwoke( _ _arg0: AppEvent_SystemSleepEvent? ) {
        systemAwoke( arg0: _arg0 )
    }

    /// public abstract void com.apple.eawt.SystemSleepListener.systemAboutToSleep(com.apple.eawt.AppEvent$SystemSleepEvent)

    private static var systemAboutToSleep_MethodID_4: jmethodID?

    open func systemAboutToSleep( arg0: AppEvent_SystemSleepEvent? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "systemAboutToSleep", methodSig: "(Lcom/apple/eawt/AppEvent$SystemSleepEvent;)V", methodCache: &SystemSleepListenerForward.systemAboutToSleep_MethodID_4, args: &__args, locals: &__locals )
    }

    open func systemAboutToSleep( _ _arg0: AppEvent_SystemSleepEvent? ) {
        systemAboutToSleep( arg0: _arg0 )
    }

}


private typealias SystemSleepListener_systemAwoke_0_type = @convention(c) ( _: UnsafeMutablePointer<JNIEnv?>, _: jobject?, _: jobject? ) -> ()

private func SystemSleepListener_systemAwoke_0( _ __env: UnsafeMutablePointer<JNIEnv?>, _ __this: jobject?, _ arg0: jobject? ) -> () {
    SystemSleepListenerBase.swiftObject( jniEnv: __env, javaObject: __this ).systemAwoke( arg0 != nil ? AppEvent_SystemSleepEvent( javaObject: arg0 ) : nil )
}

private typealias SystemSleepListener_systemAboutToSleep_1_type = @convention(c) ( _: UnsafeMutablePointer<JNIEnv?>, _: jobject?, _: jobject? ) -> ()

private func SystemSleepListener_systemAboutToSleep_1( _ __env: UnsafeMutablePointer<JNIEnv?>, _ __this: jobject?, _ arg0: jobject? ) -> () {
    SystemSleepListenerBase.swiftObject( jniEnv: __env, javaObject: __this ).systemAboutToSleep( arg0 != nil ? AppEvent_SystemSleepEvent( javaObject: arg0 ) : nil )
}

open class SystemSleepListenerBase: JNIObjectProxy, SystemSleepListener {

    private static var nativesRegistered = false

    private static func registerNatives() {
        if ( !nativesRegistered ) {
            var natives = [JNINativeMethod]()

            let SystemSleepListener_systemAwoke_0_thunk: SystemSleepListener_systemAwoke_0_type = SystemSleepListener_systemAwoke_0
            natives.append( JNINativeMethod( name: strdup("__systemAwoke"), signature: strdup("(Lcom/apple/eawt/AppEvent$SystemSleepEvent;)V"), fnPtr: unsafeBitCast( SystemSleepListener_systemAwoke_0_thunk, to: UnsafeMutableRawPointer.self ) ) )

            let SystemSleepListener_systemAboutToSleep_1_thunk: SystemSleepListener_systemAboutToSleep_1_type = SystemSleepListener_systemAboutToSleep_1
            natives.append( JNINativeMethod( name: strdup("__systemAboutToSleep"), signature: strdup("(Lcom/apple/eawt/AppEvent$SystemSleepEvent;)V"), fnPtr: unsafeBitCast( SystemSleepListener_systemAboutToSleep_1_thunk, to: UnsafeMutableRawPointer.self ) ) )

            withUnsafePointer(to: &natives[0]) {
                nativesPtr in
                let clazz = JNI.FindClass( "org/genie/com_apple/SystemSleepListenerProxy" )
                if JNI.api.RegisterNatives( JNI.env, clazz, nativesPtr, jint(natives.count) ) != jint(JNI_OK) {
                    JNI.report( "Unable to register java natives" )
                }
            }

            nativesRegistered = true
        }
    }

    public convenience init() {
        self.init( javaObject: nil )
    }

    public required init( javaObject: jobject? ) {
        super.init( javaObject: javaObject )
        SystemSleepListenerBase.registerNatives()
        createProxy( javaClassName: "org/genie/com_apple/SystemSleepListenerProxy" )
    }

    static func swiftObject( jniEnv: UnsafeMutablePointer<JNIEnv?>?, javaObject: jobject? ) -> SystemSleepListenerBase {
        return unsafeBitCast( swiftPointer( jniEnv: jniEnv, object: javaObject ), to: SystemSleepListenerBase.self )
    }

    /// public abstract void com.apple.eawt.SystemSleepListener.systemAwoke(com.apple.eawt.AppEvent$SystemSleepEvent)

    open func systemAwoke( arg0: AppEvent_SystemSleepEvent? ) /**/ {
    }

    open func systemAwoke( _ _arg0: AppEvent_SystemSleepEvent? ) /**/ {
        systemAwoke( arg0: _arg0 )
    }

    /// public abstract void com.apple.eawt.SystemSleepListener.systemAboutToSleep(com.apple.eawt.AppEvent$SystemSleepEvent)

    open func systemAboutToSleep( arg0: AppEvent_SystemSleepEvent? ) /**/ {
    }

    open func systemAboutToSleep( _ _arg0: AppEvent_SystemSleepEvent? ) /**/ {
        systemAboutToSleep( arg0: _arg0 )
    }

}
